### ISSUE TITLE
Keyboard shortcuts in activity UI

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#1002]
**User story/persona**
As a power user, I want to work quickly through transcribing and reviewing actions without having to switch from the keyboard to the mouse and back.

Examples: I'd like to use command-S or ctrl-S to save my work. I'd like to be able to change focus through the image viewer, the text editor, and the page list/ grid view using a keyboard shortcut. I'd like a "next page" keyboard shortcut.

**Comment by acdha** [comment]
I added “accessibility” to this because it can be really important for low-mobility users who are encumbered by a mouse-heavy UI. My thought would be that we should right down the steps needed to transcribe or review, identify each step which could have a shortcut, and see how consistently we can follow common desktop UI conventions.
