### ISSUE TITLE
Messages and edit behavior for review activity in new UI

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#1004]
Stems from #951 
For review mode:
- [ ] After clicking Edit: After clicking Edit, the user should get a confirm message that reads, "Thank you for helping to review this transcription! Submit when you've finished your edits." It should be possible to Save and Submit as if you're in Transcribe mode from here. If the user Submits the transcription to be (re-)reviewed, the confirm message should be "Thanks! Want to keep reviewing?" - and then provide a button that when clicked takes them to the next page to review.
- [ ] After clicking Accept: the message at the bottom should be "Thanks! Want to keep reviewing?" and then provide a button that when clicked takes them to the next page to review (button text TBD)

**Comment by acdha** [comment]
For this, does “message” mean “text which displays where the buttons you just clicked used to be”, “a modal dialog like we currently have”, or something else? I'm leaning towards the former since I feel like part of the spirit of this is not blocking the ability to do things like click on something else in the UI as a modal would.
