### ISSUE TITLE
Update activation email

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#1104]
There have been a few messages sent to us by users where the link is broken. Example below: 

![brokenlink](https://user-images.githubusercontent.com/7362915/63462437-f2a2c400-c428-11e9-9b7c-eb76b30c5961.PNG)

Update email to include edits to the text below: 

Subject header: Start transcribing! Activate your By the People account

Thank you for becoming a Library of Congress virtual volunteer with By the People!

Please verify your email address in the next 48 hours to complete activation by clicking this link:
[activation link]

Once you confirm your email, your account will be active! You'll be able to complete pages by reviewing other volunteers' transcriptions, tag pages, and see a history of your activity on your account page. 

Happy transcribing!
The _By the People_ team

**Comment by acdha** [comment]
The template for the email doesn't include any of the HTML which you can see in that screenshot:

https://github.com/LibraryOfCongress/concordia/blob/master/concordia/templates/django_registration/activation_email_body.txt

The emails we're sending look like this:

```
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Subject: Your registration at crowd-dev.loc.gov
From: crowd@loc.gov
To: chris@improbable.org
Date: Wed, 21 Aug 2019 19:49:21 +0000
Message-ID: <0100016cb5ba003e-015163da-2c5d-4e27-a0e5-72fe7fe35b07-000000@email.amazonses.com>
X-SES-Outgoing: 2019.08.21-54.240.8.42
Feedback-ID: …


Hi acdha,

Thank you for joining crowd.loc.gov! Please verify your email address in the next 48 hours.

To complete activation, please click the following link:
https://crowd-dev.loc.gov/account/activate/ImFjZGhhIg:1i0Wbh:HlBUigVNlCK1x0ooZhgREigEZr8/

Once you confirm your email, you'll be able to add tags and complete transcriptions by reviewing text - plus see a history of your work in your account page.
```

This means that the problem needs to be fixed by the email client which has a buggy process for converting URLs in plain text emails to HTML. It might be useful to learn what they're using to read the emails and see if there's a common client.

Regarding the template changes, that seems like a separate pull-request to update that template. Note that since we are using plain text emails we either need to add a multipart HTML alternative in addition to the text or use a non-linked version of the prose.

**Comment by elainekamlley** [comment]
We'll look into which email clients are reporting this issue and see if there is a common denominator. For the content, I'll be updating it and will do a PR. I removed the URLs as per your plain text comment.
