### ISSUE TITLE
"Add items" does not work for manual import - remove/hide this button

### ISSUE THREAD

**Issue by VVH** [LibraryOfCongress/concordia#1114]
I tried to import two items manually (rather than via bulk import) to new Campaign on stage; https://crowd-stage.loc.gov/campaigns/hell-upon-earth/. The items appeared on the list, but didn't pull any items or assets from loc.gov. 

**How can we reproduce the bug?**

1. Go to https://crowd-stage.loc.gov/admin/concordia/campaign/14/change/
2. Click on Items, then "Add Items"
3. Select project "Diary and letter" from dropdown list
4. Try adding: 

- Title: "Samuel J. Gibson diary and correspondence, 1864., Diary, 1864"; 
- Item url: https://www.loc.gov/item/mss52410001/; 
and Item id: mss52410001

5. When I did this and the import seemed to fail, I tried a few more times over a few days. Then I tried bulk import. This gave me a 500 error at first, I think because these items already existed from my attempt to import manually. @elainekamlley suggested I delete the manual imports, and then retry bulk. That worked, sort of, but see Issue 1113 about bulk import issues

**What is the expected behavior?**
I thought this would import the item and all assets and associate them with the project/Campaign. 

**Error Messages**
I saw a 404 or 500 error 

**Desktop (please complete the following information):**

-   Windows 10
-   Chrome, Version 76.0.3809.132 (Official Build) (64-bit)

**Comment by rstorey** [comment]
The way it's currently implemented, in order to pull images from loc.gov, you have to use the importer. The Django admin default Add Items form will only allow you to add records to the database. Populating assets in the database and pulling images is performed by the importer, and the add items default Django admin form isn't linked up to that. So I think the long-term solution is for us to implement the expected behavior: add a checkbox or something that allows you to specify whether you want to perform an import action or whether you just want to add a record to the database without importing. Either that, or put a message on the Add Items default form that clearly indicates what it does and doesn't lead people to believe that it will populate the other parts of the data model other than the Item.

Okay so in order to do what you want to do, try this:
1. Go to the Edit Project form for the project where you want the items to live. In this case it would be https://crowd-stage.loc.gov/admin/concordia/project/45/change/?_changelist_filters=campaign__id__exact%3D14
2. Click the Import Items button in the list of gray buttons at the top.
Which takes you here: https://crowd-stage.loc.gov/admin/concordia/project/45/item-import/
3. Then put the URL for the item you want to import - without any other information such as title or whatever - and click Import.

Now that the items already exist on stage, of course this process would not do anything because it won't reprocess an existing item. But you can try this process with some different items or maybe try it in dev or test. We should also add this to the admin documentation.

**Comment by lalgee** [comment]
Resolve by removing/hiding "Add item" button on Items sub-dashboard.  This function is not needed since the bulk import from Project does work.

**Comment by acdha** [comment]
We should not remove the add item feature as it is useful for testing and manual item creation. It would be less work to either use Rosie's suggestion to customize the text on the form to explain that it's only doing one of the two steps needed, add an “Import Item” link to the same row, or modify the bulk import view not to require the add item permission (i.e. deleting https://github.com/LibraryOfCongress/concordia/blob/295629d522ecfbe9ce8276d5d9f36a1a71ea11f7/concordia/admin/views.py#L115) and then that permission could be removed from people who don't use it.

**Comment by jkueloc** [comment]
Moved to Jira: [CONCD-49](https://staff.loc.gov/tasks/browse/CONCD-49)
