### ISSUE TITLE
Refactor contributions calculation to refresh on interval of time

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#1193]
Right now, the contributions calculator refreshes when a user goes into a campaign. If there are many contributors to a campaign, the load of the page slows in performance. 

Refactor the calculation to refresh on a timed interval rather than when the page loads will help speed the load of the campaign.

**Comment by acdha** [comment]
This could definitely be cached but we should probably get some examples to confirm that this what's causing the performance issue you're seeing since even uncached the campaigns pages don't take that long to load — for example, 700ms is something we could definitely improve on but it's not that far from normal:

https://www.webpagetest.org/result/200212_RM_cc90a400d46941aa8464705034640474/1/details/#waterfall_view_step1

**Comment by elainekamlley** [comment]
@rstorey was this done during the last release?

**Comment by rstorey** [comment]
Not exactly. Other changes were made that would probably make this a moot point.

**Comment by elainekamlley** [comment]
Closing to make a more accurate ticket based on the new code
