### ISSUE TITLE
Investigate the root cause of image corruption in Herencia

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#1224]
So far there have been a hand full of images that are cut off. Screenshot below. As of right now we are addressing the images as we encounter them by redownloading them to S3. This has successfully addressed the issue in the short term. 

For the long term: What are ways to investigate? Some questions to answer: 
- Is this a larger problem with our importer or the data? 
- What improvements can we do to prevent this from happening again? 

![Screen Shot 2020-04-27 at 2 20 18 PM](https://user-images.githubusercontent.com/7362915/80406810-a438a580-8892-11ea-8545-04ff038ba685.png)

**Comment by acdha** [comment]
Based on the code, the only way that the problem could be specific to the importer would be if there was an unhandled error in our upload to S3, which would have been logged. It waits for the entire file to be downloaded before storing anything permanently. We could harden that further by having [the exception handler attempt to delete the S3 object](https://github.com/LibraryOfCongress/concordia/blob/3624031fcb8780715fefed5c423ac3cb841913d4/importer/tasks.py#L525) but given the way S3 works, I think that's redundant since the S3 API won't store failed uploads.

Were these images downloaded during a period of infrastructure issues? We don't have a great way to catch that — attempting to decode the image will handle some but not all error states — but that would be my first suspicion.

**Comment by elainekamlley** [comment]
If this issue persists in other campaigns we'll reopen the ticket
