### ISSUE TITLE
Move asset status to the top of thumbnail in asset view

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1243]
**User story/persona**
As a user, I want to quickly be able to tell the status of assets when browsing the thumbnails on an asset view page.

**Is your feature request related to a problem? Please describe.**
Currently the page number is at the top of the thumbnails and the status is at the bottom. The status is more important information to a volunteer looking for a page to work on than the page order number but is harder to see when browsing.

([Example](https://crowd.loc.gov/campaigns/organizing-for-womens-suffrage-the-nawsa-records/general-correspondence-q-z/mss3413200917/?) 
![image](https://user-images.githubusercontent.com/20258744/90827061-8b547400-e309-11ea-9a1c-3f5756acde82.png)

**Additional context**
This is a recommendation from user research conducted in Winter 2020:  "Move page status above page image – “completed” more salient information than “#2”"

**Acceptance Criteria**
The page status displays at the top of the thumbnail image overlay.

**Comment by klee72** [comment]
@rabiloc I think the easiest way would be to switch the placement of status with page number.

1. Make two edits to this block: https://github.com/LibraryOfCongress/concordia/blob/master/concordia/static/scss/base.scss#L506-L513
```
.concordia-object-card .card-title {
    top: 0; // Change this to bottom: 0;
    padding: 2px;
    margin-bottom: 0; // Add this override the default margin
    font-weight: bold;
    color: var(--text-color-offwhite);
    background-color: var(--light-shadow-color);
}
```
2. Make an edit to this block: https://github.com/LibraryOfCongress/concordia/blob/master/concordia/static/scss/base.scss#L519-L521
```
.concordia-object-card .card-actions {
    bottom: 0; // Change this to top: 0;
}
```

Please let me know if this is not what you had in mind.

**Comment by klee72** [comment]
@rabiloc:

These fixes are for the comment/request "The words are a little hard to read with the opacity of the grey. Make that at little more solid and I think we would be good to go"

1. First of all I think none of the gallery view (results view ?) will pass accessibility contrast ratio due to the default opacity setting. I suggest that the opacity setting for the "card" level to be turned off since each gallery item already has a link/button in them that also has hover/focus style.

Remove below block from https://github.com/LibraryOfCongress/concordia/blob/master/concordia/static/scss/base.scss#L493-L495:
```
.concordia-object-card[data-transcription-status='completed']:not(:hover) {
    opacity: 0.5;
}
```

2. Darken status background: https://github.com/LibraryOfCongress/concordia/blob/master/concordia/static/scss/base.scss#L523-L525
```
.concordia-object-card .card-actions .btn-default:not(:hover) {
    background-color: var(--light-shadow-color); // remove this line
    background-color: var(--shadow-color); // add this line
    border-color: var(--shadow-color); // add this line
    color: #fff; // add this line
}
```

3. Unstyle title to make it consistent with other card views
https://github.com/LibraryOfCongress/concordia/blob/master/concordia/static/scss/base.scss#L506-L512
```
.concordia-object-card .card-title {
    bottom: 0;
    padding: 2px;
    margin-bottom: 0;
    font-weight: bold; 
    font-size: .875rem; // add this line
    color: var(--text-color-offwhite); // remove this line
    background-color: var(--light-shadow-color); // remove this line
    position: static; // add this line
}
```

Revert text color:
https://github.com/LibraryOfCongress/concordia/blob/master/concordia/static/scss/base.scss#L497-L504
```
.concordia-object-card .card-title,
.concordia-object-card .card-actions {
    position: absolute;
    left: 0;
    right: 0;

    color: var(--text-color-offwhite); // remove this line
}
```

Remove below block from:
https://github.com/LibraryOfCongress/concordia/blob/master/concordia/static/scss/base.scss#L515-L517
```
.concordia-object-card .card-title:hover {
    background-color: var(--shadow-color);
}
```
