### ISSUE TITLE
Multi-volume assets have different resource URLs than expected

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1255]
### Order of operations: 
- [x] Community Manager to create a csv of URLs that need to be replace with the correct ones
- [x] Dev will use csv to find and replace or any other technical solution to correct the URLs

### Context below: 

**What behavior did you observe? Please describe the bug**
The resource url imports incorrectly for all assets of loc.gov multi-volume items. This url is used for the "view on loc.gov" link on the transcription page of each assets.

All of the assets from the first volume import with the url for the volume rather than individual pages so they all point to the first page of the volume.  

- Example: the 3rd page of the first volume (4)
o	Actual url: https://www.loc.gov/resource/rbc0001.2018houd14646v4/
o	Concordia url (links to 1st page): https://www.loc.gov/resource/rbc0001.2018houd14646v4/?sp=4

Additionally, all assets that are in volumes other than the first volume are broken links. The resource url for all of these is assembled with the correct p1 identifier but with the url structured for the first volume in the item.
-	Example:  the last page of the last volume (scanning target).
o	Actual url: https://www.loc.gov/resource/rbc0001.2018houd14646v15/?sp=392
o	Concordia link (broken): https://www.loc.gov/resource/rbc0001.2018houd14646v4/?sp=4652

**How can we reproduce the bug?**
Look at "Seers, Spiritualists, and the Spirit World: The experiments of Frederick Hockley" campaign  or "Test Campaign" in stage.

**What is the expected behavior?**
Resource url field should contain the correct url linking directly to the page on loc.gov

**Additional context**
Planning to launch the multivolume Hockley campaign in October 2020.

Related issue: https://github.com/LibraryOfCongress/concordia/issues/1254

**Comment by acdha** [comment]
The importer is correctly saving what P1 refers to as the resource URL. For example, if you look at the JSON data for the first URL you mentioned, you'll see that it has the same resource URL:

https://www.loc.gov/resource/rbc0001.2018houd14646v4/?sp=4&fo=json

```
cadams@Ganymede ~> http 'https://www.loc.gov/resource/rbc0001.2018houd14646v4/?sp=4&fo=json' | jq .resource.url
"https://www.loc.gov/resource/rbc0001.2018houd14646v4/"
```

Based on the expected behaviour you describe, I think this would be a matter of adding a rule to favor the value of what P1 calls a segment over the resource URL when both are present:

```
http 'https://www.loc.gov/resource/rbc0001.2018houd14646v4/?sp=4&fo=json' | jq '.segments[].url'
"https://www.loc.gov/resource/rbc0001.2018houd14646v4/?sp=4"
```

That could easily be done by changing this line:

https://github.com/LibraryOfCongress/concordia/blob/30f85821d10d9b4860a4a83a9c730972291445ba/importer/tasks.py#L436

However, at the very least we'd need to figure out whether there are cases where this would cause unexpected behaviour on other items and from the other requests it might be the case that this is really asking for the data model on Concordia to be extended to have full support for multi-volume items if there are ever cases where we might want to display both of these values in different context.
