### ISSUE TITLE
Add padding to Help Center cards

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#1259]
The bottom of the help center cards are flush with the footer

**Comment by acdha** [comment]
This appears to be for mobile screen sizes, right? We might also want to tweak the space between the cards as they can bunch up horizontally under around 992px.

**Comment by lalgee** [comment]
This is for desktop as well - the issue was created when we moved the FAQ to the About page.  This is how it the page appears on my PC in Chrome:
![image](https://user-images.githubusercontent.com/20258744/94059153-08af5080-fdb0-11ea-90a7-0c7823552ddf.png)

**Comment by acdha** [comment]
That's why I said “screen sizes” because it only affects small screen sizes. The gap between the cards collapses at 992px and narrower. The bottom footer triggers at 935px.

This is due to the footer height being set to 149px except on the smallest width — when the layout switches to the vertical layout – and could likely be addressed by adding a slight margin to the footer element:

https://github.com/LibraryOfCongress/concordia/blob/a606f3b10c1c56a9bca388645120a77f4580e5e8/concordia/static/scss/base.scss#L994-L998

Since doing that globally would affect the entire site it'd either be important to scope it to just the help center or by adjusting the padding and margin at the same time so we're shifting some of the padding to a top margin but not changing the height of the footer (e.g. set `padding: 18px 0` and `margin-top: 4px`). This section hasn't had much attention in a long time so it might be good to get @klee72 to review it in general since it has pretty basic styling.

**Comment by klee72** [comment]
Sorry I know that I have some UI tickets for overall refinements and I think this page was one of them. I'm going to try to get to these tickets soon. However since it's going to take some time for me to get setup for the project again, I think the short term solution would be to remove the fixed `width` value and add a bottom margin for each item so that they have some space in between.

```
.help-center-card {
    color: #fff;
    // width: 300px;  // Remove this
    height: 225px;
    background-color: var(--primary-color);
    margin-bottom: 1rem; // Add this
}
```
