### ISSUE TITLE
Overview of count of items and assets before importing

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#1261]
**User story/persona**

- As a user I want to have a overview of the count of items and assets I am about to import so that I can check if what I am importing is accurate
- As a user I want to be able to see a full count of items and assets before import so that I can confirm if I want to move forward with that import

**Is your feature request related to a problem? Please describe.**
Currently when we are importing a bulk set of items/assets, we don't know if we have all the items and assets accounted for until after the importing has happened and we do our standard checks in the campaigns dashboard. We find this count in the admin dashboard by filtering down. 

**Acceptance Criteria**

- See a count overview of items and assets that will be imported
- Be able to confirm or cancel import if the count is inaccurate

**Acceptance Test:**
- Create two different spreadsheets with different item numbers and assets
- Go to bulk import on the admin dashboard
- Choose file and select a import spreadsheet
- click import
- See an overview of item and asset count and compare to initial numbers
- See Import or Cancel buttons
- Click Import
- Do regular checks to confirm if all assets

**Comment by elainekamlley** [comment]
Feedback: Add total count

**Comment by lalgee** [comment]
Tested on 8 different bulk import spreadsheets.  The largest spreadsheet it worked on was 53 rows. The smallest spreadsheet it crashed testing was 155 rows. So the limit is somewhere between 50-150 rows.

When it works, it works well.  However about half of By the People imports are over 150 rows, and most of those larger imports range between 400 and 2000 rows. It is these larger imports for which this feature is most needed.

**Comment by acdha** [comment]
I think the number of assets is more significant than the number of items but looking at the code here, I'm not sure that matters. #1286 doesn't have any review or test history so I'm not sure what has been done but it doesn't appear to me that it's actually running the code asynchronously. 

The loop in https://github.com/LibraryOfCongress/concordia/blob/95f947d075517c5337bc3e3d33b0594f354152b0/concordia/admin/views.py#L187-L198 executes synchronously so it will perform very similar to the original code. I suspect that the intention was to use something like `asyncio.gather()` which would allow the requests to be fetched concurrently rather than waiting for each one in sequence. That would look like this:

```python
#!/usr/bin/env python3

import asyncio
import random


async def fetch_url(url):
    print(f"{url} slept")
    await asyncio.sleep(2)
    print(f"{url} woke")
    return random.randint(0, 100)


async def fetch_all_urls():
    futures = [fetch_url(f"http://example.org/{i}") for i in range(20)]
    ret = await asyncio.gather(*futures)

    return sum(ret)


print("Returned total:", asyncio.run(fetch_all_urls()))
```

It may also not be the case that we see much value from using asyncio in this case and would like to throttle the maximum number of requests which could be made at a time to avoid overloading the origin server, at would point I would be inclined to suggest the use of `concurrent.futures` and threading:

```python
#!/usr/bin/env python3

import concurrent.futures
import random
import time


def fetch_url(url):
    print(f"{url} slept")
    time.sleep(2)
    print(f"{url} woke")
    return random.randint(0, 100)


def fetch_all_urls():
    urls = [f"http://example.org/{i}" for i in range(20)]

    with concurrent.futures.ThreadPoolExecutor(max_workers=8) as executor:
        result = executor.map(fetch_url, urls)

    return sum(result)


print("Returned total:", fetch_all_urls())
```

**Comment by rabiloc** [comment]
Thanks @acdha Yes I was trying to make the code async, but didn't seem like that was actually happening. I will give the code you wrote above a shot and see how the performance improvements. I think the plan was to go over all the items in the excel sheet and display the asset count, so the BTP folks can validate with their script.
