### ISSUE TITLE
Review scan and investigate various spam flags

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#1280]
There have been various AWS spam flags in the last few weeks. Here are some examples:  

- Activation emails are being flagged as spam. Need to see if emails are used to registered. Some of them are used real looking emails and some are various characters. Ex. 
```
"Hi dctdjkjleirf,
Thank you for becoming a Library of Congress virtual volunteer with By the People! "
```
- There has been an a spam email that sent by us: 
```
Contact crowd.loc.gov: Invest $ 15,000 in affiliate marketing and get $ 45,000 in a month
```

Look into our email services in AWS to what is being flagged as spam and cross check account activations. Potential need to add more steps like captcha in the registration and the contact form to protect from spamming in the future.

**Comment by acdha** [comment]
I suspect what happened is that a spammer created a robot which stuffs random people's contact information into the form and is relying on the feature which sends a copy of the message to the provided email address. Since the contact form needs to be open, the two options which come to mind are removing the courtesy copy or to trying things like requiring a CAPTCHA for anonymous contacts. The latter approach is something of an arms race — IP-based limits usually won't be effective since spammers typically use large numbers of compromised machines — so it'd probably be easiest to either remove the courtesy message or change it to a generic “We have received your request…” message which does not contain any user-entered values when it's sent by a user who has not been verified.

**Comment by rabiloc** [comment]
Received scan results from the security team, going over the list to see which ones an be resolved
