### ISSUE TITLE
Make clearer visual distinction between completed/available projects/items/assets thumbnails

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1303]
**User story/persona**
As a volunteer, I want to easily be able to tell what is available for me to work on by looking at the project, item, and asset thumbnails. 

**Is your feature request related to a problem? Please describe.**
It is not currently easy to tell which pages are completed based on the grey overlay on thumbnails. Perhaps the overlay should be darker and there should additionally be a color tint or text overlay of DONE for completed items. 

It could also be useful to create visual identities for each status that could match the progress bar/status filters.

**Additional context**
![image](https://user-images.githubusercontent.com/20258744/103030655-3da37e80-452a-11eb-80e2-819c1e04ea7e.png)
The project on the left is completed, the project on the right includes pages still needing work. The only visual indicator is that the image appears slightly lighter and there is a slight difference in the color of the text. When you hover over the completed thumbnail it returns to "normal". While these are visual indicators of the project's completeness they are not at all obvious.

**Acceptance Criteria**
There is a clear visual indicator in the thumbnail of completed projects/items/assets that makes it obvious to any user that those materials are done.

**Comment by elainekamlley** [comment]
@klee72 Any suggestions for @jkueloc for this?

**Comment by klee72** [comment]
@elainekamlley @lalgee @jkueloc 
I think the problem currently with the “completed” items/assets is that they're “greyed out” but it’s not disabled (links and pages are still active), therefore it makes them inaccessible with contrast compliance.

My suggestion is 
Remove all grey-out styling for “completed” status from all pages.
Reuse “complete” label from item detail page on project detail page. (Fig1)
Update all labels/buttons other than “completed” to use primary blue color (Fig2).

I did a quick code changes using browser inspect and grabbed some screenshots below.
.
Let me know and I can work on this with [@jkueloc.
<img width="1249" alt="fig1" src="https://user-images.githubusercontent.com/3189000/110371090-82638f80-801a-11eb-8a31-fa550b80729c.png">
<img width="1162" alt="fig2" src="https://user-images.githubusercontent.com/3189000/110371122-8abbca80-801a-11eb-9f74-af958cd68dd6.png">

**Comment by elainekamlley** [comment]
@klee72 Thanks for the examples! I understand the greying out the text causes accessibility issues. However, do you see issue with greying out of the image? The complete header is great but adding another grey overlay would reenforce to the user that it is done. Thoughts?

**Comment by klee72** [comment]
@elainekamlley Yep I think greying out the images should be fine since 'complete' labels will be added. If this is the only comment then I can try to get this done in the current sprint. Let me know.

**Comment by elainekamlley** [comment]
Yup, that is the only comment!

**Comment by klee72** [comment]
@elainekamlley @lalgee is it 'completed' or 'complete' for the label?

**Comment by klee72** [comment]
@lalgee @elainekamlley 
Updates have been pushed to dev/test. Can you click around all detail pages when you have a chance and let me know? Below are summary of the updates:
- Updated all detail pages as described in the ticket
- Removed drop-shadow from cards to make it consistent with item-detail cards and in line with P1 styling
- Updated styling of 'Related links' box and 'View this item on www.loc.gov' button to meet contrast compliance
- Fixed overall spacings of the page, so that all elements/layouts on the page take advantage of the available width
- Improved responsive design of the gallery
- Added 'zoom in' hover effect (thought it was strange for only 'completed' ones have a hover effect)
- Added spacing between gallery and pagination

**Comment by lalgee** [comment]
A few points of feedback @klee72 :

- cards are no longer centered on page. This is especially striking when there's [only one card](https://crowd-test.loc.gov/campaigns/hockley/the-crystal/) It's also awkward/confusing when paginated since the 3rd row of [a "full" page](https://crowd.loc.gov/campaigns/organizing-for-womens-suffrage-the-nawsa-records/general-correspondence-h-p/?page=4) only has only 2 justified to the right, which implies that there are no additional images, even when there may be pages more.
- the distinction between cards that are available/unavailable for activity still isn't as clear as we would like, but i wonder if the best way for us to keep iterating would be to pull https://github.com/LibraryOfCongress/concordia/issues/1246 into an upcoming sprint
- the size of card image has changed - can you give us those dimensions for image editing? (we manually create the project images)

**Comment by klee72** [comment]
@lalgee 
Yes I agree and it's a good idea to change the progress bar colors so that the blues are tied to 'active' items and gray is tied to 'complete' items. I'm attaching some screenshots from my local environments:
- Changed 'complete' progress bar color to light/medium gray
- Changed 'needs review' progress bar color to primary blue
- Slightly darken 'in progress' blue so that there is a contrast difference from 'complete' gray
- Changed 'not started'  progress bar color to white bg / primary blue border
- Changed 'completed' status link color to dark gray
- Changed 'completed' image's opacity from 50% to 40%

Also I've updated the gallery items to be center aligned. And cards and its image have gotten slightly larger because it's extended to the container width. I made the adjustment so that the dimension is same as before, you wouldn't need to change dimensions of images.

Let me know
<img width="1221" alt="Screen Shot 2021-04-01 at 10 40 58 AM" src="https://user-images.githubusercontent.com/3189000/113314088-ea378e00-92d9-11eb-9541-19b1cb2a89dc.png">
<img width="1192" alt="Screen Shot 2021-04-01 at 10 41 28 AM" src="https://user-images.githubusercontent.com/3189000/113314095-ec015180-92d9-11eb-8143-7e50949090a9.png">
<img width="1191" alt="Screen Shot 2021-04-01 at 10 41 50 AM" src="https://user-images.githubusercontent.com/3189000/113314107-eefc4200-92d9-11eb-9dc9-cc7db17e053e.png">

**Comment by lalgee** [comment]
Thanks, @klee72 ! Using something besides blue for completed is great and really helps to make the materials available for activity stand out!

Is it possible to use a darker shade?  This might sound silly, but the grey feels a little anticlimatic when completion is something we really celebrate and want to feel like "YAY! COMPLETE!" to our users.

**Comment by klee72** [comment]
@lalgee 
Here are dark/darker gray versions, I'm using the same gray for 'complete' button/label. Just know that there should be enough contrast difference from two blue colors. Also 'complete' button/label can replace the progress bar once it's completed. Let me know.

Dark gray:
<img width="1205" alt="gray-dark" src="https://user-images.githubusercontent.com/3189000/113702416-787b8d80-96a7-11eb-8db8-a7a083cbf2cc.png">

Darker gray:
<img width="1191" alt="gray-darker" src="https://user-images.githubusercontent.com/3189000/113702487-8f21e480-96a7-11eb-8682-675e96eaf1fc.png">

A label replacing progress bar - dark gray:
<img width="1228" alt="label-middle-dark" src="https://user-images.githubusercontent.com/3189000/113702614-bc6e9280-96a7-11eb-8c92-132bfefd677f.png">

A label replacing progress bar - darker gray:
<img width="1179" alt="label-middle-darker" src="https://user-images.githubusercontent.com/3189000/113702671-d4dead00-96a7-11eb-8b94-f29928e3c055.png">

**Comment by lalgee** [comment]
Thanks again for iterating with us, Ki!  We really like the darker gray!  We also like the idea of replacing the bar with the completed label but wonder what that would look like at the asset level when there are also still materials to transcribe/review and that label is at the top.  Do you mind mocking that up?

**Comment by klee72** [comment]
@lalgee label/button on top is still best option for item detail since the height of images are incosistent. However I think label/button should not be overlay on images here as this is where users can preview the images to transcribe. Let me know.

<img width="1174" alt="item-detail" src="https://user-images.githubusercontent.com/3189000/113736057-cbb30780-96ca-11eb-83c0-3aa4aa96ae32.png">

**Comment by lalgee** [comment]
Hi, Ki.  That makes sense.  Let's move ahead with the dark gray and the progress bar switching to completed when all are done.

**Comment by klee72** [comment]
@lalgee These updates have been pushed to dev/test. Please take a look and let me know.
