### ISSUE TITLE
Make responsive transcription box larger by reducing the amount of space tags take up on page.

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1339]
**User story/persona**
After the most recent design update to improve responsiveness (https://github.com/LibraryOfCongress/concordia/issues/1319), some users are still reporting the transcription box as uncomfortably small.

**Is your feature request related to a problem? Please describe.**
In most cases this seems to be an issue of the responsive design on smaller screens with pages that have several tags. It also is worsened in "Edit" mode. Could likely be improved by prioritizing transcription box size over other display space for other less used functions such as tagging. 

Users' descriptions of and screenshots of the issue are documented in a thread on History Hub: 
https://historyhub.history.gov/thread/10395

**Comment by abshelton** [comment]
As a users, I would like the transcription box to stay a consistent size during the review process. Currently, the box shrinks by a few lines when you select "edit" on a page in the review queue. The box shrinks even further if there are more than one line of tags. Some screenshots are below. 

Example: https://crowd.loc.gov/campaigns/lincoln-raisins/the-remaining-letters-to-lincoln/mal3968700/mal3968700-2/
First image is before selecting edit, second is after selecting edit. 

![Screenshot (81)](https://user-images.githubusercontent.com/79859582/126662841-3a71d6b3-35a9-47e6-b54c-3069cc2ec6ab.png)

![Screenshot (82)](https://user-images.githubusercontent.com/79859582/126662930-f185f4de-6b44-408e-bf87-e56dd4e4fe68.png)

**Comment by lalgee** [comment]
The issue is worse for those assets with many tags.  Can we keep tags to a single line, perhaps with a scroll bar?

Here's an example and user story recently sent by volunteer Dorothy:
I am having trouble reviewing a page because only 2 lines of text appear in the transcription box. Usually I can see 10 lines of text.

This is the page in question:  https://www.loc.gov/resource/mss34132.mss34132-047_00612_00671/?sp=31

I am using an iPad and the Firefox browser.

There were a lot of tags added to this particular page. I was thinking perhaps that might be the reason for the problem.

**Comment by klee72** [comment]
@lalgee 
Yes it's possible to make the tags a single line but not sure if increasing 1-3 lines would be enough. Also since it's going to hide all tags other than first 3-4 by default, I’m assuming that it’d be difficult to use if there are more tags.

May I suggest:
1) To make the "Tags" area collapsible? Expanded by default but can be collapsed to use the entire right column for editing.
2) Currently the transcription screen minus the header & bredcrumb & footer is supposed to fit the height of the browser window. We can exclude the top bar (pages, fullscreen and etc) and the bottom bar ("need help?”) as well.

I'm attaching screenshots, let me know your thoughts.

Expanded (default):
<img width="1295" alt="expanded(default)" src="https://user-images.githubusercontent.com/3189000/134008778-2b408b1b-adda-45c4-8b28-36c0b3be35ee.png">

Collapsed:
<img width="1289" alt="collapsed" src="https://user-images.githubusercontent.com/3189000/134008890-3badf20b-0f4c-4571-b17c-cc3f3165d9c3.png">

**Comment by lalgee** [comment]
@klee72 this looks great!  We'd like to move ahead with this design -- the only change is that we'd like it to be hidden by default.

**Comment by klee72** [comment]
@lalgee: updates have been pushed to dev/test. Please review and let me know.

**Comment by lalgee** [comment]
@klee72  it looks great and is working well in dev and test!  Since we're doing default closed, would it be possible to add something to indicate when there are already tags?  Maybe a tag count next to the word Tag?  Happy to add as a separate ticket.

**Comment by klee72** [comment]
@lalgee Yes I also think that the tag count would definitely be helpful.  Please go ahead and create a new ticket and I'll try to get to it in sprint 22.

**Comment by lalgee** [comment]
Great, I will ticket and am now passing to @Igor-Ino for QA.

**Comment by Igor-Ino** [comment]
When I go full screen in Safari, it shows empty page, screen shot is attached.
It might be deserving a new ticket.
<img width="1000" alt="Screen Shot 2021-09-29 at 21 34 37" src="https://user-images.githubusercontent.com/80710853/135371618-3172d2d8-8088-4be9-8f46-2e4f57681c79.png">

**Comment by klee72** [comment]
@Igor-Ino Thanks for finding the issue. It looks like it's broken in production as well, and we should handle it in a separate ticket as tag ui update is not the cause of the issue. TY

**Comment by Igor-Ino** [comment]
Tested, looks good.
