### ISSUE TITLE
Make it easier for volunteers to find instructions via "Help" dropdown

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1340]
**User story/persona**
As a user, I want to be able to find the instructions and navigate to them quickly so that I can answer my questions about how to contribute.

**Is your feature request related to a problem? Please describe.**
User testing in winter 2020 showed that users do not intuit where to find instructions. Currently users have to click through an unnecessary landing page to get to the instructions and then choose which area of the instructions they need.  This could be improved by eliminating the [Help landing page](url) from the navigation by turning "Help" in the navigation bar into a dropdown menu of the 4 instruction pages so users can go directly to what they need. 

The pages that should appear in the dropdown are the welcome guide, how to transcribe, how to review, and how to tag. They should be listed as 

- [Get started](url)
- [Transcribe](url)
- [Review](url)
- [Tag](url)

**Additional context**
This dropdown functionality is already present for "Account" in the current navigation bar.
![image](https://user-images.githubusercontent.com/20258744/108898219-f2b6ed80-75e4-11eb-9540-d9af660d9f0f.png)

Related issue - https://github.com/LibraryOfCongress/concordia/issues/1341 Rename Help to How-to

**Acceptance Criteria**
As a user, I am able to navigate directly to each of the 4 instruction pages from any BTP page using a dropdown in the navigation bar.

**Testing plan**
As a user 
When I click on the How-to nav tab I see a drop down menu of 
THEN I see a drop down menu of 
- [Get started](url)
- [Transcribe](url)
- [Review](url)
- [Tag](url)

As a user
WHEN I click on one of the How-to drop down menu items
Then I am taken to that How-to page

**Comment by jkueloc** [comment]
@elainekamlley @lalgee this change is now in dev and test if you would like to take a look there.

**Comment by Igor-Ino** [comment]
Tested in test environment, looks good. 
Out of scope of this ticket:
The red type, specified in CSS as var(--primary-color), and blue type, specified in CSS as #0076ad, are very low contrast and will be rejected by Accessibility review.

**Comment by lalgee** [comment]
Looks good to me in test.

**Comment by lalgee** [comment]
Looks good to me in test.

**Comment by lalgee** [comment]
@jkueloc @elainekamlley what do we need to do regarding Igor's note above about accessability?

**Comment by jkueloc** [comment]
@lalgee @elainekamlley @Igor-Ino 
It shouldn't stop this ticket from moving forward for the coming release - as Igor notes it is out of the scope for this ticket/
I would be interested in what @klee72 would recommend
It should be it's own ticket or perhaps become part of broader Accessibility review/remediation...?

**Comment by klee72** [comment]
@lalgee @elainekamlley @Igor-Ino @jkueloc 
Currently there are many css variables (example: var(--primary-color)) being used on Concordia, especially for colors. This is because the project has been using the precompiled Bootstrap css where we couldn't customize the theme from more deeper level. We've recently switched over to SASS version of Bootstrap, and I was able to replace some colors into SASS variables. However I was hesitant to replace all colors in css variables to sass variables because I haven't gotten to the transcription detail page yet, which seems to have many variables (different colored buttons and etc) that I'm not familiar with yet. It'd be more clear for me once I start working on the transcription detail page, where I plan to do some cleanup of css variables simultaneously. 

For accessible colors, Amanda and Jamie have already created a color schemes (https://www.sketch.com/s/490a19aa-6608-4ae3-8118-a0e8b0222fb0) for P1 and other sites that share the look & feel. These color update has been applied to P1, libguides, ask a librarian, pcwa and etc, and will be applied to Concordia project soon.

Please go ahead and create a ticket for me to clean up transcription detail page.

**Comment by lalgee** [comment]
@klee72 Thanks Ki.  I'll ticket.
