### ISSUE TITLE
Concordia no longer automatically updating Kibana dashboard.

### ISSUE THREAD

**Issue by abshelton** [LibraryOfCongress/concordia#1367]
**What behavior did you observe? Please describe the bug**
The By the People Kibana dashboard is no longer displaying live activity data from Concordia for reporting metrics. It looks like this is the case as of 03/09/2021-after which point there is no further data. This issue last occurred in November 2020.

**How can we reproduce the bug?**

1. Go to https://go.usa.gov/xszUd (Kibana link is super long so I've shortened it). 
2. Scroll down to the data visuzalizations related to site activity on the page (ie. "Anon vs. registered transcriptions activity" or "Transcription statuses per day."
4. If you hover over the last bar or indicator in those visualizations you can see that the last date recorded was 03/09/2021.

**What is the expected behavior?**
Kibana should be pulling from the Concordia logs once per day and display this activity data in the public dashboard. 

WHEN a user looks at the By the People Kibana dashboard,
THEN they should see data from the last 24 hours appearing in all sections of the page. 

**Got screenshots? This helps us identify the issue**

![Screenshot (16)](https://user-images.githubusercontent.com/79859582/112525080-e73b1b80-8d76-11eb-8a53-39c83a9d9d70.png)

**Desktop (please complete the following information):**

-   Windows, Chrome

**Additional context**
Kibana is pulling user data as it should but not data about activities (like transcriptions, etc)

**Comment by jkueloc** [comment]
Currently, the data in Kibana is through 4/9/2021. Still stale. But I'm looking into it.

**Comment by jkueloc** [comment]
@abshelton The frequency of the periodic process didn't change.  Apparently, there is more than one task that runs as seen in the Admin Periodic Task section.  Which also shows that populate ES indices ran at midnight.  So it's running daily - but there's an issue.  I'll keep looking into it.

**Comment by jkueloc** [comment]
Update - error messages seem to be pointing to space issues. I increased the EBS volume from 10 GiB to 20 GiB. And see how the population of elastic search indices goes tonight.

**Comment by jkueloc** [comment]
@lalgee probably - I would need to figure out how to do that.   Meanwhile - the EBS increase may get it moving again. 

I have also wondered in general the same thing about the campaigns within Concordia  - do they need to live there forever since it's a multipurpose tool?  If not, what's the decision process for deciding when what can be removed.

**Comment by lalgee** [comment]
Concordia was always intended as a passthrough application. I hope we'll be able to start articulating "sunsetting" features for campaigns soon and work on development next fiscal year.

**Comment by jen** [comment]
Hi Y’all! I’m @jen, but it seems you have the wrong Jen. —Jen Burke
  	 Industry
Visual / Interface Design
T 415 552 3111 W industrious.com
1459 18th Street #131 San Francisco CA 94107
Pronouns: it, it, its (it's is not a pronoun)

**Comment by jkueloc** [comment]
@lalgee The population of elastic search indices completed successfully last night. 

Some extra details:
The process ran for ~ 2hrs 23ms.  
It builds in 5 indexes.  'User', UserAssetTagCollection', 'SiteReport', 'Asset', and 'Transcription'.  
The first four sets took ~ 38ms with 'Transcriptions' taking up the remainder fo the runtime.    
I'm wondering if maybe just the 'Transcriptions' could be limited to a 6 month period and not all of them. 
Is 6 months long enough?
 
So, we can keep an eye on it. For now the space looks good. Of the 20 GiB there remains 9.19GiB.
It may make more sense to control the volume of data in one place through Concordia "sunsetting" (front door) rather than more complex index population (buried in details of the black box).  But I'm sure there is an argument for either way.
