### ISSUE TITLE
Incorrect font used for breadcrumb, making error in transliterated text, using special characters for diphthongs 

### ISSUE THREAD

**Issue by Igor-Ino** [LibraryOfCongress/concordia#1448]
**What behavior did you observe? Please describe the bug**
Incorrect font used for breadcrumb, making error in transliterated text, using special characters for diphthongs 

**How can we reproduce the bug?**

1. Go to  https://crowd-test.loc.gov/campaigns/herencia-centuries-of-spanish-legal-documents/next-reviewable-asset
2. See breadcrumb Konstitutsiya encoded incorrectly

**What is the expected behavior?**
Konstitutsiya encoded correctly

**Got screenshots? This helps us identify the issue**
Add screenshots to help explain your problem.

**Desktop (please complete the following information):**

-   OS: OS X, Windows
-   Browser CHROME only

**Additional context**
![Chrome](https://user-images.githubusercontent.com/80710853/119175404-ca019100-ba37-11eb-923e-c36734ba9888.jpg)

**Comment by Igor-Ino** [comment]
Tested, looks good. There is ani proportional diacritics in FF, I think it is due to incorrect rendering. Looks great in Edge, Safari and Chrome.

**Comment by acdha** [comment]
This is a blast from the past — the last time I encountered issues with this particular fallback path was 8 years ago, and it appears that the Firefox issue has remained open since then:

https://chris.improbable.org/experiments/browser/combining-half-marks/

The workaround @klee72 picked is better for consistency but it does make me wonder whether we might find Arial or the other system fonts a better choice for the UI text in general since those are aggressively tested to handle a wide range of languages and settings.
