### ISSUE TITLE
Users reporting slow loading and timeouts

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1463]
**What behavior did you observe? Please describe the bug**
Users are reporting transcription pages are slow to load and sometimes timeout loading or saving.  Admin is also loading very slowly.

When I sit on a page in a browser window for more than 5 minutes or so, I get a error message on the page "unable to reserve" and then when I try to refresh sometimes I get a timeout.

**How can we reproduce the bug?**
Steps to reproduce the behavior:  Go to transcription pages in various campaigns. Attempt to save, submit or edit pages.

**Desktop (please complete the following information):**

-   OS: Various including Windows 10
-   Browser: Various including Firefox and Chrome

**Additional context**
User stories:
- Everything is very slow, if it works at all.
- System has refused to save every single one of the first six pages I've worked on this morning. There is clearly a problem with your system. I'm using Windows 10 and I've tried both Firefox and Chrome, and the problem has existed on both browsers. I am repeatedly receiving gateway "time out" messages. In fact, I got such a message when I sent this first note to you.
- TIME OUT ERROR crowd.loc.gov Host Error ALL PAGES in crowd.loc.gov since yesterday afternoon. I'm sure you're working on it
- Website is loading very slowly and sometimes not at all.

**Comment by jkueloc** [comment]
Noticed the CPU utilization was high post upgrade to PostgreSQL v12 despite running ANALYZE. Then volunteers starting exerience frustrating time outs, etc.  Some searching had several reports of upgrades to v10 and above not using indexes and doing sequence scans instead. WIth @acdha guidance, ran Explain Analyze against the database and  https://explain.dalibo.com for graphical representation to confirm that Concordia was experiencing the same behavior. 
One report (https://dba.stackexchange.com/questions/282271/postgres-11-query-plan-uses-seq-scan-after-upgrade) also mentioned experiencing some relief modifying a parameter. Which didn't seem to help us much. But there are excellent references in the post.  So, experimenting with Vaccum turned out to be the best short term performance bump.  VACUUM (VERBOSE, ANALYZE) was run on specific hot tables first followed by the all of the Concordia tables.  
Will research for further indexing opportunities (which are needed anyway post pandemic use growth) and perhaps more performance tuning after that.
