### ISSUE TITLE
Kibana data has incorrect asset counts

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1509]
**What behavior did you observe? Please describe the bug**
The Kibana asset count does not match the actual count in the Concordia production database. 

**How can we reproduce the bug?**
1. Go to the [BTP Kibana dashboard](https://crowd.loc.gov/_plugin/kibana/app/kibana#/dashboard/30cdf6d0-65f8-11e9-be0c-ed8cfbe18dbf)
2. Note the number of "Total" assets displayed in the top widget
3. Go to the Concordia django admin [assets dashboard](https://crowd.loc.gov/admin/concordia/asset/)
4. Click the "select all" checkbox to see the total count of assets in the database
5. See that the actual asset count does not match Kibana's

**What is the expected behavior?**
Kibana should update every night with a data from the Concordia production database. It's possible the Kibana index population doesn't really purge and rebuild the indexes from scratch. 

We also need to determine if the index population does a complete rebuild from scratch. Figuring out what is duplicated and how it happened (if possible) and then remediating would take time, so it may be quickest to just figure out how to empty the data (documents) and repopulate it from scratch.

**Got screenshots? This helps us identify the issue**
Kibana:
![image](https://user-images.githubusercontent.com/20258744/126384687-22333d5d-e100-4d37-9247-b969d58f9a45.png)

Concordia:
![image](https://user-images.githubusercontent.com/20258744/126384756-904b2f1f-05ba-4b10-be42-740428ca2887.png)

**Comment by jkueloc** [comment]
CA: Maybe some of the deleted records are still in Kibana? (This could possibly be a reimport).
_If you can get record IDs or project counts that’d narrow it down._

JK: I remember that there were issues loading some campaigns or projects. Is it possible some were loaded twice or loaded partially one day and then fully the next?..or possibly deleted one day and reimported the next?   A conversation I had with another developers included the word ephemeral when discussing AWS ES so my understanding was that they indexes were completely recreated.  _I need to confirm that_. I was trying to extract the duplicate slugs since that seemed to be a key value.  You may be able to filter duplicates from any dashboards that may have incorrect totals.You may be able to filter duplicates from any dashboards that may have incorrect totals.

LA: That is possible. At several points the wrong content (including a large chunk of Whitman) was accidentally imported and those records/assets were then deleted. It shouldn't be possible to bring the same asset in twice but I'm sure it could have happened somehow?

JK: ...So figuring out what is duplicated and how it happened (if possible) and then remediating ... We would need to know for certain if the es index population does a complete rebuild from scratch. It may be quickest to just figure out how to empty the data (documents) and repopulate the data from scratch.

**Comment by lalgee** [comment]
Following up with additional info about misaligned Kibana data. This issue is not just for assets but tags as well.

Exploring Concordia tags in Kibana, I discovered that count is also off.  I believe the tag data available in Kibana is for distinct tag records (aka every time a record is created for a new unique term) rather than tag usage.  As of today there are 104,319 distinct tags in the Concordia database but Kibana shows a lifetime count of 71,093.

**Comment by jkueloc** [comment]
Moved to Jira: [CONCD-21](https://staff.loc.gov/tasks/browse/CONCD-21)

**Comment by jkueloc** [comment]
This issue is closed as the work has been moved to the Library's Jira repo as noted above.
