### ISSUE TITLE
Profile "pages worked on" is incorrect and pagination is broken when viewing "All Campaigns"

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1556]
**What behavior did you observe? Please describe the bug**
When a user visits their profile page, the "pages worked on" list is not updated to show recent contributions. The most recent it shows for me is June 2021, thought I have made many reviews and transcriptions since then. 

Additionally, the list just repeats when you try to look at the next page of results via the numbers at the bottom of the screen. The first (incorrect) page of “pages worked on” just repeats over and over again as you page through what should be different lists of contributions.

When I filter to a specific campaign, my contributions do appear (though there is a bug for some review contributions  -- see https://github.com/LibraryOfCongress/concordia/issues/1557)

**How can we reproduce the bug?**

1. Log in
2. Submit a transcription or accept a page than needs review
2. Go to Profile page
3. Scroll down to "Pages worked on" while viewing "All Campaigns"
4. Your recent actions will not appear

**What is the expected behavior?**
The "pages worked on" list should show all assets I have recent transcribed or reviewed, which the most recent actions listed first.  It shows up to 12 actions.  If I have taken more than 12 actions on the site, the list should paginate. When I click to the next page it should show me actions 13-24, etc.

**Additional context**

**Comment by lalgee** [comment]
tested in dev and this issue appears resolved!

**Comment by jkueloc** [comment]
Update:  Seems there is a bug when order_by is just a datetime field when using pagination. https://stackoverflow.com/questions/5044464/django-pagination-is-repeating-results.  I applied this workaround at least for now and it solves the pagination (rows repeating after 15 records - initially sequentially and then in small groups of rows disbursed with new rows of data.  

I also change to one date column for aggregating the user_id and reviewed_by_id records - because the nulls and the various current sorts seemed to not be playing well together.
