### ISSUE TITLE
Admin S3 Object Deletion - Epic

### ISSUE THREAD

**Issue by jkueloc** [LibraryOfCongress/concordia#1573]
Research what's needed to add deletion of S3 object to the admin module

Original ticket for reference #1090 & #1257

Course of action: 

- Implementation strategy: #1574 
- Add Image File Field:  #1575
- Populate field: #1593

**Comment by jkueloc** [comment]
Three approaches - high level
1. Create an admin action for the asset model in the admin module/app use boto3 directly to delete the asset object
2. Modify the Asset model: Add a custom delete to asset model itself based on the approach above - so when a  asset is deleted however it's also deletes the related S3 object  directly with boto3 (would need to add prefetch to item level delete) 
3. Modify the Asset model: Add the s3 object (image file url) as a FileField. As I currently understand it, when a delete is requested for asset the Django framework will handle the lower level S3 delete.

**Comment by acdha** [comment]
Creating it as a FileField or even an ImageField shouldn't be too much of a change — they're stored internally as text fields in the database so it's just a question of how the framework handles it — but I think the bigger question would be how to approach batching. 

This is basically making the bulk deletes even more expensive and so it would have the same solution: instead of doing something like `item.assets.delete()` you'd want to do something like a `values_list()` queryset with `more_itertools.chunked()` to retrieve the keys a thousand a time and pass them to the boto3 S3 client's `delete_objects()` method en masse before doing a bulk database delete for the same reason.

**Comment by jkueloc** [comment]
@acdha Regarding cost - should the S3 deletion stay a separate process and not integrate it into application?

**Comment by acdha** [comment]
> @acdha Regarding cost - should the S3 deletion stay a separate process and not integrate it into application?

There's a bit of a judgement call there — the cleanest way to do something like this architecturally would be to toss the delete request for *everything* into a queue and have a worker process it. That allows it to take as long as needed, it can retry, etc. and we already have Celery setup so the infrastructure is there. 

The downside is basically figuring out the UI messaging strategy since you're basically saying “I submitted the request, here's where you can view the status” and either having that last part be something like status updates from the worker nodes or simply letting them hit reload and watch things disappear.

Alternatives I've used are things like making a streaming HTTP response (to avoid timeouts) and sending status updates live or, later, using WebSockets for the same reason. I'm not sure this is worth doing anything fancy, however.

**Comment by jkueloc** [comment]
>@acdha This is basically making the bulk deletes even more expensive and so it would have the same solution: instead of doing something like item.assets.delete() you'd want to do something like a values_list() queryset with more_itertools.chunked() to retrieve the keys a thousand a time and pass them to the boto3 S3 client's delete_objects() method en masse before doing a bulk database delete for the same reason.

> @acdha There's a bit of a judgement call there — the cleanest way to do something like this architecturally would be to toss the delete request for everything into a queue and have a worker process it. That allows it to take as long as needed, it can retry, etc. and we already have Celery setup so the infrastructure is there.

Is there any benefit to the first solution you mentioned ....values_list() before pursuing a celery solution or are they mutually exclusive?
  
At this point I think adding the s3 object (image file url) as an ImageFile and handling bulk delete requests by tossing it into a queue for a celery worker to process makes the most sense without out any fancy alternatives.  Then iterate through the UI messaging strategy starting with "hit reload and watch things disappear."

**Comment by acdha** [comment]
> Is there any benefit to the first solution you mentioned ....values_list() before pursuing a celery solution or are they mutually exclusive?

They work at different levels so you could do either one. The thing we're trying to avoid is having a big loop processing them one-by-one:

```python
for item in items:
    for asset in item.assets.all():
       asset.delete() # Class method will delete from S3 at one object per call
```

You can use large queryset chunks to reduce number the inner loop calls by a factor of a thousand:

```python
for chunk in more_itertools.chunked(assets.filter(item__in=items).values_list("filename", flat=True), 1000):
   S3.delete_objects(Bucket=…, Delete={"Objects": [{"Key": i} for i in chunk])
``` 

That might mean that it happens quickly enough that you don't need to do anything more. If not, Celery allows you to decouple the web page response generation from the actual work at the cost of needing to build the function around an asynchronous UI. That might look something like this:

```python
for item in items:
    purge_item.delay(item.pk)
```

… and then having the web page either do something like poll the status from an API or simply tell the user to wait a few minutes. This would work well even in a Celery task since the tasks will complete faster if you batch the operations even if you no longer have a short timeout.

You can explore using the database-backed messages to communicate errors back but that approach does require some care when dealing with large numbers of items since you wouldn't want to enqueue one message per asset or something like that. That could work well in the sense of having the message trigger at the level you told it to process the deletion — e.g. if I delete an entire project, send the message from the top (“Unable to delete project x: …”) rather than at the asset or item level.
