### ISSUE TITLE
Create site functionality explainers with popovers in Asset View

### ISSUE THREAD

**Issue by colefemeno** [LibraryOfCongress/concordia#368]
**Is your feature request related to a problem? Please describe.**
As a user, I may not know what tag, save, etc buttons are meant to do. I would like to have an explanation when I hover over these buttons. 

**Describe the solution you'd like**
Create bootstrap popovers with friendly text to describe functionality and availability of those functions.

**Describe alternatives you've considered**

- Create graphical modal
- Include in FAQ
- Let people learn by doing

**Additional context**
![rickeyassetpage](https://user-images.githubusercontent.com/31018169/46837472-7446b180-cd83-11e8-84f6-44ad49211610.png)

** To Do**

- [ ] Identify places that need explainer
- [ ] Create text 
- [ ] Identify post-launch testing for boostrap popovers

**Comment by colefemeno** [comment]
Places that need popovers: 
- Page navigation < >
- Find a New Page
- Transcription 
- Nothing to Transcribe
- Tags
- Quick Tips
- Questions

Possibly on image viewer and metadata

**Comment by colefemeno** [comment]
Suggested text: 
Page navigation < > - Select a page to view or use these arrows to navigate to a new page
Find a New Page - Move to the next page in this item that needs help
Transcription - Type what you see on the image in this field
Nothing to Transcribe - Click this button if there is nothing to transcribe in the image. Unsure? Check these Tips [[HELP CENTER LINK]]
Tags - Registered users can add tags and review other people's transcriptions. Create an account or sign in here [[LINK]]
Save - Use this button to save the text you typed above
Submit - Use this button when you’re sure there is nothing remaining to transcribe in the image
Edit - Use this button if you see some errors that need to be corrected
Accept - Use this button once you are certain the text is accurately transcribed
Quick Tips - Get short guidance to help with transcribing and review
Questions? - Connect with the Help Center, discuss in History Hub or get in touch with a Community Manager

**Comment by elainekamlley** [comment]
Here are the mocks:

![transcribe-anon-nothingtotranscribe-help](https://user-images.githubusercontent.com/7362915/48079888-5ae62900-e1ba-11e8-84ba-aca6a31c47f9.png)
![transcribe-anon-nothingtotranscribe](https://user-images.githubusercontent.com/7362915/48079891-5cafec80-e1ba-11e8-861e-ef20c7306007.png)

**Comment by acdha** [comment]
We have https://getbootstrap.com/docs/4.1/components/popovers/ ready as soon as the text is ready

**Comment by colefemeno** [comment]
Great @acdha! Revised text based on mocks 

- Page navigation < > arrows- Use these arrows to select a page to view or navigate to a new page
- Find a New Page Button- Move to the next page in this item that needs help
- Transcription field - Type what you see in the image in this field
- Nothing to Transcribe Checkbox - If it looks like there’s nothing to transcribe, use this button and then Submit. Not sure? Check these Tips [[HOW TO TRANSCRIBE LINK]]
- Tags field/Tags title  - Registered users can add tags and approve transcriptions. Create an account or sign in here [[LINK]]
- Tags ADD Button - Use this button to add tags
- Tags Save Tags Button - Use this button to save tags that you’ve added to the page
- Save - Use this button to save the text you typed above
- Submit - Use this button when nothing remains to transcribe and someone else can review
- Edit - Use this button if you see errors in the text that need to be corrected 
- Accept - Use this button once you’re confident that the text is accurately transcribed
- Quick Tips - Get short guidance to for transcribing and review
- Questions? - Find answers in the Help Center, discuss in History Hub, or report an issue to a Community Manager

**Comment by acdha** [comment]
I’m concerned about how many additional icons that would add, especially for relatively standard controls like the pagination. Should some of those be tooltips without the icon or should we be adding an overlay where clicking ? would explain many of the controls at once?

**Comment by elainekamlley** [comment]
Good questions @acdha - here's my proposal, what do you think @colefemeno?

### Hover text for buttons: 

**Tagging**
- Tags ADD Button - Use this button to add tags
- Tags Save Tags Button - Use this button to save tags that you’ve added to the page

**For open for edit**
- Save - Use this button to save the text you typed above
- Submit - Use this button when nothing remains to transcribe and someone else can review

**For review**
- Edit - Use this button if you see errors in the text that need to be corrected 
- Accept - Use this button once you’re confident that the text is accurately transcribed


### Add icons to things that are more complicated (three in total): 
- **Find a New Page Button**- Move to the next page in this item that needs help
- **Nothing to Transcribe Checkbox** - If it looks like there’s nothing to transcribe, use this button and then Submit. Not sure? Check these Tips [[HOW TO TRANSCRIBE LINK]]

**Need help?** Condense this as one icon
- Quick Tips - Get short guidance to for transcribing and review
- Questions? - Find answers in the Help Center, discuss in History Hub, or report an issue to a Community Manager

### Not needed at this time:
- Page navigation < > arrows- Use these arrows to select a page to view or navigate to a new page (since this is common across other apps)
- Transcription field - Type what you see in the image in this field (We can update the language in the text box now and we have this language in the quick tips) 
- Tags field/Tags title  - Registered users can add tags and approve transcriptions. Create an account or sign in here [[LINK]] - (We have this message here for anonymous users)

**Comment by acdha** [comment]
I'm not entirely in love with “Use this button” prefixing most of them. I was wondering whether we should add more text describing the effects of a button — e.g. “Save the text you entered above and continue transcribing” or “Request that someone else review the text which you entered above”.

https://developer.apple.com/design/human-interface-guidelines/macos/user-interaction/help/ has some good guidelines — in particular, I like the advice to start with a verb — as does https://developer.apple.com/design/human-interface-guidelines/macos/buttons/help-buttons/

**Comment by elainekamlley** [comment]
I'm for it!

**Comment by elainekamlley** [comment]
@acdha Could we remove the `?` on the want to tag msg for anonymous and add to the message to say `Want to tag this page? Register or Login to add tags.`

**Comment by elainekamlley** [comment]
This is done.
