### ISSUE TITLE
UI Updates - Campaigns page

### ISSUE THREAD

**Issue by colefemeno** [LibraryOfCongress/concordia#382]
Campaign page needs revision

- [x] Representative image size
- [x] Intro field should be enlarged
- [x] Campaign title font may need to change in size

**Comment by jbresner** [comment]
I've reduced the font size for all the <h1>s. Here's the CSS:

.h1 {
  width: 334px;
  height: 40px;
  font-family: RobotoSlab;
  font-size: 40px;
  font-weight: bold;
  font-style: normal;
  font-stretch: normal;
  line-height: 1;
  letter-spacing: normal;
  color: #333333;
}

I'm not sure what's meant by the "Intro Field"—maybe the campaign description? If so, here are the specs for that:

.campaign-desc {
  width: 662px;
  height: 74px;
  font-family: OpenSans;
  font-size: 18px;
  font-weight: normal;
  font-style: normal;
  font-stretch: normal;
  line-height: normal;
  letter-spacing: normal;
  color: #333333;
}

Finally, for the representative image size, here are the specs:

.campaign-feature-img {
  width: 466px;
  height: 345px;
}

Because there will be a limited number of campaigns, I'm wondering if we could manually create these images instead of displaying the entire image inside a container.

**Comment by jbresner** [comment]
![campaigns - list](https://user-images.githubusercontent.com/4275957/46921237-c0cdff00-cfc6-11e8-8d20-3ef5caaacd59.png)
