### ISSUE TITLE
Refining height responsiveness for smaller screens

### ISSUE THREAD

**Issue by colefemeno** [LibraryOfCongress/concordia#444]
**What behavior did you observe? Please describe the bug**
When tags are added to a page during the edit state and saved and a user then goes to the page to review, the window displaying the text that requires review is presented as only a few lines

**How can we reproduce the bug?**
You will need two logged in accounts or to toggle between admin and registered user account
1. Go to  a page, enter transcription text. Save. 
2. Enter enough tags to create two lines of tags. 
3. Submit the page.
4. As a different user, enter the page which is now in Review state. 
5. The text field displaying the transcription may be impacted by the number of tags - especially if the browser size has been reduced (see below).

**What is the expected behavior?**
As a user who wants to review, it should be as clear as possible for me to see as much of the transcribed text as possible when I arrive on the page. 

**Got screenshots? This helps us identify the issue**
![tagsimpactreview_19oct18](https://user-images.githubusercontent.com/31018169/47237175-41687300-d3ac-11e8-92bf-26808668a4a3.PNG)

**Desktop (please complete the following information):**
Working in Chrome

**Comment by acdha** [comment]
This is really a broader issue of responsiveness on unusual aspect ratios. In the screenshot, the total size is shorter than the average phone display so there's not really a wait to make everything visible.

Currently, the tag list is constrained to only grow to 15% of the total screen height. We can change that so that would include the label & registered user message but it might be better just to set a reasonable minimum height for the entire viewer since it's also hard to read the image other otherwise work when all you have is a 400 pixel region.

Capping the entire tagging area would look like this:

![image](https://user-images.githubusercontent.com/46565/47240375-1d119400-d3b6-11e8-91d0-4c006a64c8b8.png)

Setting a min-height would look something like this, which seems reasonable since you can also use full-screen mode to get an extra few pixels back:

![image](https://user-images.githubusercontent.com/46565/47240552-9e692680-d3b6-11e8-9ce3-dcbd48a6ba2e.png)

The other question is whether we should make tagging collapsible so a reviewer could choose not to deal with it at all – that'd look something like this:

![image](https://user-images.githubusercontent.com/46565/47240486-737ed280-d3b6-11e8-975d-ed1f076d35a2.png)

**Comment by colefemeno** [comment]
@cadams setting min height sounds like a great start to ensure the first portion of text can be viewed when someone lands on the page, plus help them visually assess if they want to take on that reviewing challenge. 
For the 3 views you shared:
- Could we go with Option 1 for anonymous and combine the two “Tags” and “only registered...” lines into a single line by changing the text to “Tags - log in or create an account add your own” to better express an enhanced task functionality rather than a limitation?  
- For registered volunteers, I’m interested in options 2 & especially 3 when initially presented in the reviewing state. 
- For Option 3 - the “show tags” button corresponds to what is shown in the “Submit”/Accept modal (the “add tags” button), so that seems like a starting point for reminding folks it’s possible to tag. @jbresner any thoughts about having “Show”/“Hide” tags in the UI? Anyone have thoughts about See vs Show vs Add for that button?

Also @jbresner can we talk about ways to test these options and help keep a volunteer in the flow and integrate tagging tasks?

**Comment by elainekamlley** [comment]
@colefemeno @acdha what is the status of this ticket? From the looks on the site, the minimum height is set with the merge of #444. From my perspective it looks like some work has been done and potentially can be closed?

**Comment by elainekamlley** [comment]
Updated text was added as per @colefemeno suggestion: 
![screen shot 2018-12-05 at 5 15 39 pm](https://user-images.githubusercontent.com/7362915/49554523-745dbc00-f8b1-11e8-9d7f-d01ab9c60709.png)

The hiding/show tags is another feature. I'll create that ticket and close this.
