### ISSUE TITLE
Social Share from the Asset Page

### ISSUE THREAD

**Issue by colefemeno** [LibraryOfCongress/concordia#475]
User stories: 

- As a user, I want to easily share the link to the page I'm working on in a social network or a short link. Also I may want to share the link to the entire item (diary, letter, etc) from the Item page. 
- As a user I am so excited about this one letter and I want to share directly to either Facebook, Twitter, or email(?), or copy a short link so that I can show my family and friends how awesome it is. 

Problems we are trying to solve: 
- users can share an asset 
- capture basic metrics of sharing behavior

Updated acceptance criteria (based on research and conversations below): 
- [ ] Add share links on the asset level for Facebook, Twitter, email, and copy link to clipboard 
- [ ] When a user clicks Facebook, Twitter and email those links open another browser window or mail app signaling that that user is moving out of crowd.loc.gov
- [ ] When a share link has opened a new page, to build trust with our users,  there is a timed message saying that the user is now leaving crowd.loc.gov, before opening the external social platform 
- [ ] A message dialogue in the external platforms will include a short description from the title, a link to crowd.loc.gov, and campaign code
- [ ] When a user clicks copy link there is a message that pops up saying `this link has been copied`
- [ ] Add campaign codes to each link (need to follow up on what campaign codes go where)

**Comment by rstorey** [comment]
As part of this we should consider what will show up as the preview image on FB, Twitter when someone posts a link to the site.

**Comment by elainekamlley** [comment]
An acceptance criteria to consider - build a function that could be adopted library wide.

**Comment by acdha** [comment]
#669 added the `og:image` meta header which many things (i.e. Facebook, Twitter) use for the thumbnail when sharing. We could add those to the item & asset pages but there's a big caveat: those images are potentially *MUCH* larger. I'd be tempted to examine the API response metadata which we're storing for each record to see if there's a more appropriate loc.gov URL which we could reference instead.

**Comment by elainekamlley** [comment]
@jbresner if you have time, do you mind adding the update to this?

**Comment by jbresner** [comment]
Michelle Springer appears to still be investigating whether AddThis is a viable option for a share tool. A reply to her question on the GSA's Social Media Community of Practice listserv suggested this as an alternative: https://github.com/usinterior/ncshare.

**Comment by acdha** [comment]
In addition to the privacy risks, one of the arguments for removing AddThis from wdl.org was the substantial page weight — if memory serves, that pulled in more JavaScript + CSS than the rest of the site. We should measure the performance cost as part of the comparison.

**Comment by jbresner** [comment]
...and just as a reference, here is the link to the Negotiated Terms of Service Agreements on the Digital.gov website: https://digital.gov/resources/negotiated-terms-of-service-agreements/ (direct link to the PDF: https://s3.amazonaws.com/digitalgov/_legacy-img/2014/07/addthis-updated-tos-amendment.pdf)

**Comment by elainekamlley** [comment]
Update: We will be moving forward with building our own for just Concordia. Next steps is adding this in our road map and updating the Acceptance criteria based on: 

- Desired features ex. pop out text editor or open new page 
- Design of share tool UI 
- Analytics we want to capture when a users shares a link that aligns with our privacy and disclaimer policies

**Comment by elainekamlley** [comment]
Some considerations: 

How much do we want to inform users about going to a third party like twitter or fb. An example [CFPB](https://www.consumerfinance.gov/external-site/?ext_url=https%3A%2F%2Ftwitter.com%2Fintent%2Ftweet%3Furl%3Dhttps%253A%2F%2Fwww.consumerfinance.gov%2Fabout-us%2Fblog%2Fcredit-score-myths-might-be-holding-you-back-improving-your-credit%2F%26amp%3Bvia%3DCFPB%26amp%3Btext%3DCredit%2520score%2520myths%2520that%2520might%2520be%2520holding%2520you%2520back%2520from%2520improving%2520your%2520credit%2520--%26amp%3Brelated%3Dcfpb&signature=kr4pw7uFx4bswWEu1--A8G15uCA) has a disclaimer page right before going to a social platform

**Comment by jbresner** [comment]
It's not exactly the same thing.

CFPB looks like it displays the disclaimer when a user clicks on a link to the social media channel (e.g. CFPB's Facebook or Twitter page). Instead of this approach, we display an external link icon next to links that leave any of our root URLs (e.g. LOC.gov). The one notable exception is in our footer where we don't have those links next to each social media icon since it was assumed a user would understand that the social channels (e.g. Facebook) are not LOC.gov.

For sharing on LOC.gov (for something like Facebook), a new window opens allowing the user to create a post and then share it. An interstitial message letting a user know that a Facebook window is about to appear would seem unnecessary (and in our case, not required).

I'd argue that sharing, as an activity on our site, should be as frictionless as possible.

**Comment by acdha** [comment]
I think it's also somewhat addressable with the UI text: if we had, say, a bunch of links with the different services which open in a new window it seems like someone who clicked “Share on Facebook” would understand that's visiting Facebook and we're not leaking their privacy if we don't load anything from facebook.com before that click.

**Comment by rstorey** [comment]
The current implementation which is in the social-share-asset feature branch is missing the following from the original ticket description, and I'd like these things to be ticketed and addressed separately:
* URL shortening
* Intermediate timed message about leaving crowd.loc.gov
* Email icon (as per our convo)
* Campaign codes (we'd need to register as an app with FB and Twitter for this sort of tracking)

**Comment by acdha** [comment]
URL shortening is generally considered to be an anti-pattern. Since we have good, stable URLs we should discuss what problems it's trying to solve before committing to doing anything with it.

I don't know what other discussions have happened with email but generally just putting a `mailto:` URL in is the best way to have it work portably, especially on mobile.

For campaign codes we should clarify what the goals are. It should be easy to add URL parameters for this usage to at least tag the source since our sharing URLs don't include query strings or fragments which would avoid needing to parse the URLs & insert them (which would require a polyfill as long as we need to support IE11, which doesn't support the [`URL`](https://caniuse.com/#feat=url) or [`URLSearchParams`](https://caniuse.com/#feat=urlsearchparams) APIs).

**Comment by jbresner** [comment]
One issue to consider when using the `mailto:` is that will launch an email app. For mobile users, that probably will never be an issue. For desktop/laptop users, especially ones in schools/libraries (or anything that's on a shared device), the email application launching won't be set up to be used for the user. In those cases, the user is more likely to have a webmail setup, which won't automatically work with `mailto:`.

Also, even though it's certainly easier to set up a link using `mailto:`, some users may find it a little jarring to have a new app launch by clicking on a link. Definitely something worth testing and knowing who is most likely to be using this feature.

**Comment by acdha** [comment]
@jbresner Definitely a good point to test — most browsers now allow using a webmail provider as the mailto: URL handler but I don't know how common it is to have that configured. Google has characteristically added it and then broken the UI for at least some Gmail users.

I'm also not sure whether any of this is especially useful on mobile since the broswers there tend to have prominent sharing buttons so metrics might tell us whether or not we even want to fit this on smaller screens or perhaps collapse it selectively.

**Comment by elainekamlley** [comment]
As per our email, @rstorey here is the labels for Adobe user interaction. Let me know if you need anything else. 

User Interaction | Category | Action | Label
-- | -- | -- | --
User shares content on Facebook | Share Tool | click | Facebook Share
User shares content on Twitter | Share Tool | click | Twitter Share
User copies content url | Share Tool | click | Link Copy
