### ISSUE TITLE
Address Internet Explorer Compatibility 

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#515]
Decide on course of action to make crowd.loc.gov compatible in IE

**Comment by acdha** [comment]
We should identify specific areas and prioritize them. Much of the site is functional in IE11 but the homepage has some custom CSS which needs updating — basically anything in https://github.com/LibraryOfCongress/concordia/blob/master/concordia/static/css/base.css which mentions ”flex” needs reviewing since without something like autoprefixer those don't have the fallbacks which the Bootstrap classes include.

**Comment by colefemeno** [comment]
As a user coming to the site using IE, I would like to be notified that my experience might not be optimal with this browser. I could see this message in a banner or modal when I land on the page.

**Comment by acdha** [comment]
@colefemeno Do we want a simple modal or something like the https://browser-update.org/ ribbon?

**Comment by rstorey** [comment]
See https://github.com/LibraryOfCongress/concordia/pull/539#issuecomment-434758192

**Comment by rstorey** [comment]
If we want to do more with IE compatibility, let's ticket specific issues separately.
