### ISSUE TITLE
Double image in the viewer 

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#572]
**What behavior did you observe? Please describe the bug**
on a few of the assets, there is a duplicate image in the viewer. The second image flashes as I zoom in and out of the viewer. 

[Here is an example](https://crowd.loc.gov/campaigns/letters-to-lincoln/1850-1857-death-and-birth-of-children-and-re-entry-to-politics/mal0069200/mal0069200-4/) 

**How can we reproduce the bug?**
1. Go to that asset by clicking the link above and see image
2. Zoom in and out or move to different parts of the image and see the second image flicker

**What is the expected behavior?**
Just have one of the images and not a repeating one

**Got screenshots? This helps us identify the issue**

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Firefox

**Comment by acdha** [comment]
See https://github.com/openseadragon/openseadragon/issues/1297 and https://github.com/openseadragon/openseadragon/issues/1113.

Since we're using an old vendored copy of OpenSeadragon the very first thing I'd do is replace it with OpenSeadragon 2.4.0 from https://cdnjs.com/libraries/openseadragon to see whether the problem reproduces.

**Comment by acdha** [comment]
I cannot reproduce this problem after #583 updated to 2.4.0

**Comment by elainekamlley** [comment]
Considered closed after #583
