### ISSUE TITLE
OpenSeadragon tweaks

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#582]
Make the controls always visible
Make the controls look like the rest of the site

**Comment by acdha** [comment]
I was going to take this on later today. What I was thinking:

1. Disable the built-in controls entirely
2. Add a row of btn-xs buttons (i.e. real `<button>` so all of the usual accessibility options apply) either above or below the viewer
3. Select the appropriate Font Awesome icons for consistency with the rest of the UI
4. Review the keyboard accessibility situation: add a global binding for "?" and "h" which opens a help panel and consider some combination of either adding shortcuts using meta keys so you can use them while typing in the textarea or shortcuts to switch focus to the viewer, transcription text area, and tag input. This all means that we probably also need to review event bubbling so keyboard events originating in the text inputs don't reach the global handler.

Since #4 is big, it could reasonably be a separate ticket.
