### ISSUE TITLE
Update help center to clarify transcription and review instructions

### ISSUE THREAD

**Issue by VVH** [LibraryOfCongress/concordia#615]
There has been some confusion among users (expressed via email, HH and in person) about where to find instructions. We can tighten things up to make this clearer. 

Also, I want to add a section on what to do about abbreviations. We probably want to ask people to expand these if they can so that the data becomes more searchable. Alternatively, tell people not to expand, but to add tags. i.e. Wm. could be transcribed as William or Wm. We should decide which.

**Comment by colefemeno** [comment]
@acdha yes, I think so - In my view, all of these things relate to onboarding and situational context-seeking. Instructions, popovers, and selective guidance for tasks at hand will likely (should ideally) inform and support each other!

**Comment by lalgee** [comment]
Just noticed noticed an inaccuracy in the How to Review instructions. They state that you can make corrections and then accept a transcript during review - https://crowd.loc.gov/help-center/how-to-review/

@elainekamlley - Since the work of this ticket is just CMs making content updates can we add it in Sprint 15?

**Comment by VVH** [comment]
Good catch @lalgee. Do you want to make the changes? We can go through how to later today?

**Comment by lalgee** [comment]
That would be great.  Tomorrow looks pretty full but if not then, my Friday’s very free.
