### ISSUE TITLE
Display a disclaimer regarding historical content

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#64]
Acceptance Criteria: 

- [ ] As a [user], I want [action] so that I can [result].

**Comment by VVH** [comment]
This is now available in the FAQ page:

**Historical materials, offensive language, explicit content**

The language and terminology used in the historical materials on this site reflect the context and culture of their creators, and may include words, phrases, and attitudes that would now be deemed insensitive, inappropriate or factually inaccurate, or may not be appropriate for all ages. Views expressed in historical documents do not reflect the views of the Library of Congress. Because the purpose of Make Your Mark is to make the Library’s collections searchable, we ask that all original content be transcribed as it appears in the original material. If you find some material offensive or upsetting, please choose something else to transcribe. If you have questions or comments regarding the material you encounter during your participation here, please contact a Community Manager via crowd[at]loc.gov, the “Contact Us” link or join or start a new conversation on the History Hub discussion forum. [link]

**Comment by elainekamlley** [comment]
This is done
