### ISSUE TITLE
Mocks of latest page redesign

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#660]
Context: 
We conducted a spike around the latest page and decided to not spend too much time building out layouts and functionality for announcements within the application but instead take advantage of History Hub features. This issue addresses the need for a wireframe of consolidate content and directing users to the discussion forum. 

User stories: 
- As a community manager I need to quickly update our volunteers with latests news so that they know about new features, challenges and events 
- As a community manager, I would like to direct our volunteers to History Hub so that they can learn more details about the announcement and connect with other volunteers 

Acceptance criteria: 

- Remove `Latest` page and add this section to `About` 
- `Latest` section will have a Title, date and lead in sentences before linking out to History Hub
- Take advantage of History Hub CMS by linking out to expanded details
- Home page has a `latest` section
- Be able to update this content without creating a release version, related to #616

**Comment by lalgee** [comment]
One thing to add above:  Press Coverage section of "Latest" should also move to About page.

Additionally, I have emailed History Hub folks about enabling a RSS feed for our HH blog posts.

**Comment by lalgee** [comment]
History Hub folks report that the current lack of RSS functionality is a bug that should be resolved in early January.

**Comment by jbresner** [comment]
I've updated the "About" page to include the Latest News content.

The three sections (Latest News, Library of Congress News, and Press Coverage) would each display a limited number of items (3 items each for now). There's also a link for the first two sections to view "more" of each category:

1. The Latest News link would go to the History Hub page (https://historyhub.history.gov/community/crowd-loc/content?filterID=contentstatus%5Bpublished%5D~objecttype~objecttype%5Bblogpost%5D).
2. The Library of Congress News link would link to a P1 canned search result page of just Crowd-related news releases.

To help with scanning latest news, the articles are listed with dates in reverse chronological order. The Press Coverage has the additional media source name listed above the date.

Finally, I took a first pass at adding all of this "news" content as a module on the home page. If we limit this to only the "Latest News", the content will end up looking sparse against everything else on the home page, which is why I kept the three sections together. One alternate approach could be displaying just "Latest News" but adding a short description (or the first paragraph) as a lead into the article. Let me know if you'd like to see a version of this mocked up as well.

![about](https://user-images.githubusercontent.com/4275957/49457960-db984500-f7b9-11e8-82ad-c10c63b64502.png)
![home-latest-news](https://user-images.githubusercontent.com/4275957/49457961-db984500-f7b9-11e8-8bc1-1c704bfe3d14.png)

**Comment by lalgee** [comment]
The latest page updates look good to me!  My only question is if we want titles listed before dates or after (as you have it). @elainekamlley @colefemeno @VVH ?

How/if to add to homepage should probably be held until we have a longer discussion re: other planned updates, like a stats dashboard etc. But I think it looks good as an option to consider!  Another might be just having the one most recent item from each column (keeping the "More" underneath) to make it less of a vertical space hog.

**Comment by jbresner** [comment]
Because the items are listed by reverse chronology, I thought it would make more sense to keep the date displayed first. But it's really a stylistic decision since we're only featuring a few items. Probably not a problem if we decide to flip it.

**Comment by VVH** [comment]
As mentioned in stand up, I think we want to centralize information in top nav rather than add to home page. Looking back at the issue @elainekamlley logged I see that there was a suggestion of having latest/news on home page as well as consolidated under 'About'. I think we agreed to hold off on these changes for a sprint or two and that homepage redesign is not essential for now, but that some of the other things in this ticket might be--i.e. consolidating tabs and moving educator links from footer into top nav, rebranded as "Resources".

**Comment by jbresner** [comment]
If we're just changing the label to "Resources" I can update the comp. However, if the existing "For Teachers" page needs updated as well, that really should be a separate ticket.

**Comment by lalgee** [comment]
The For Teachers page doesn't need a design update at this point.

**Comment by VVH** [comment]
At some stage we'll want to pull "For Educators" up into top nav and rename "Resources" but the page itself doesn't need a redesign at the moment.

**Comment by elainekamlley** [comment]
Move mocks into confluence and add Latest to About
