### ISSUE TITLE
Item statuses are not updating on user profile

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#676]
**What behavior did you observe? Please describe the bug**
User story shared by a volunteer via email:
On my profile page there is a list of the documents I have worked on. Many of them say "In Progress". However, when I click on the link to the document, it shows as complete. 
I experienced the bug on my account page as well.

**How can we reproduce the bug?**
1. As a logged in user, visit your account page.
2. Scroll to an item you have worked on that says "In Progress" and click the item link.
3. In nearly every case the item is now complete.

**What is the expected behavior?**
The item status on the user profile page should accurately reflect the worked-on-item's current status.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Additional context**
Possibly linked to work of #621 and #532

**Comment by acdha** [comment]
The status displayed is for the portions which the user actually worked on (i.e. transcription records). As part of #532 I'm changing that to list only the items and make it unique so submitting multiple transcription records as part of the same asset would count a single time rather than each time they hit save and/or reviewed.

**Comment by elainekamlley** [comment]
Yea I think what could be useful to volunteers is to see how they contributed as well as the status of the asset. Eventually the user seeing that they submitted it for review and then track if its complete or still in review. Its a bit hard to track if you have multiple listings of the same asset. So good catch @acdha

**Comment by acdha** [comment]
Good catch by @lalgee, I was just back-filling an explanation for what's being shown now. We've been talking about coming back to that since before the launch but now seems like a good time to actually do so. I'll post some screenshots in #532 later today but my current branch is changing this to do a list of items grouped by campaign and project, perhaps with a count of unique pages touched, and changing the layout a bit to handle our longer titles.
