### ISSUE TITLE
Make already activated account page friendlier

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#704]
**Is your feature request related to a problem? Please describe.**
As a user, when I click on the activation link in an email, and my account is already active, I am frustrated to see the message "Registration failed". The message is confusing and makes me think I can't use the site.
![image](https://user-images.githubusercontent.com/20258744/49762378-92ebfa80-fc97-11e8-86f3-20d2501a20b5.png)

**Describe the solution you'd like**
Change the message to be welcoming and encourage the user to stay and use the site.  Suggestion:
Account Active
This account has been activated.  Welcome!  [Log in here] to get started. 

**Describe alternatives you've considered**

**Additional context**
Relates to #607

**Comment by acdha** [comment]
Should this page even do something other than redirect them to the login page?

**Comment by lalgee** [comment]
Good call.  Yes, if it actually just redirects to login, I think that would take care of it.

**Comment by rstorey** [comment]
So I recently made other changes that automatically log the person in when the activate successfully. In this case, it's possible to encounter the "activation failed" message while already logged in. So in the PR #1132 I just changed the title of the page so it doesn't say "Failed" above the error message if someone accidentally double-activates. Because they might already be logged in.
