### ISSUE TITLE
Export campaign site reports each in their own sheet

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#720]
**Is your feature request related to a problem? Please describe.**
As a community manager I want to be able to easily analyze/utilize report data by campaign or all assets.  Currently the data is exported sorted by date, with all campaign data looping within the rows.  I have to extricate the individual campaigns to analyze data for each (image below)
![image](https://user-images.githubusercontent.com/20258744/50017572-79e69080-ff9a-11e8-8afe-a01658491b37.png)

**Describe the solution you'd like**
It would be preferable for the report to export export total data and data for each campaign in its own csv (example image below, though it shows tabs for each rather than individual files).  So if we have 5 campaigns, 6 files would export:  1 with data for everything in concordia and 1 for each campaign's specific data.
![image](https://user-images.githubusercontent.com/20258744/50017436-08a6dd80-ff9a-11e8-9444-b69993371696.png)

**Describe alternatives you've considered**
If the admin interface can support it, it would be great to allow community managers to choose if they want a report of everything or for specific campaigns.

**Additional context**
This feature request comes from testing of #385

**Comment by acdha** [comment]
Could you explain more about what you're trying to do? It sounds like this could be done with the existing site reports using Excel's built-in data filtering support to select a particular campaign first.

Generally speaking, doing this in Kibana would be similar using a sum aggregation rather than by changing the data.

**Comment by elainekamlley** [comment]
if I'm understanding @lalgee correctly, the user story would be

As a community manager, when I click the site report link a number of separate csvs would download. One full site report + x number for each campaign so that it reduces the amount of time of parsing though the numbers and being able to report on the application's performance

**Comment by acdha** [comment]
I was hoping to get more information about the questions being answered and the relation between the admin site reports and Kibana. That would help answer questions like whether the work should be done using the built-in support in Excel, Numbers, etc., changing the interface to download a ZIP file with multiple exports, or by instead generating an XLSX file with multiple sheets.

**Comment by acdha** [comment]
Some example questions: “I would like to prepare a graph showing the percentage completion for each campaign over time” or “I want to see the time to completion trend for the Branch Rickey campaign”.

**Comment by elainekamlley** [comment]
This a automated version of the report that Lauren and others generate by hand every week. Right now the current question is, I would like to know the total numbers of the each campaign by date. This is granular overview sitewide as well campaign specific. The follow up from testing of this is being able to separate each report so its easier to read. By refining the layout of this spreadsheets, that would get us closer to be able to determine those specific questions we want to answer.

**Comment by acdha** [comment]
Isn't that just a matter of using Excel to sort by campaign and then date so it'd be easier to see how those numbers have changed over time?

**Comment by elainekamlley** [comment]
Yes, I think its clear it can be done on Excel. Lauren's example screen shot makes tells me its possible but if we can help out Community managers by making this feature just a little more refined, it would save them a lot of time and remove one less thing they have to do on a day to day basis, while minor, could be a huge win in their experience. So is this more complicated than I'm interpreting this request?

**Comment by acdha** [comment]
I'm trying to get this specified well enough that we can say whether it's a minor request. If we're saving only a couple of seconds out of a larger process it's probably not worth doing unless we can save time elsewhere in that process, especially since some of the possibilities like exporting multiple files will cancel out most of the time savings with the extra file management overhead. 

Documenting the context could help avoid that by producing exactly what's needed. For example, if the goal is simply to get the latest total numbers for the site & each campaign for a weekly email we could make sure that that data is cleanly copyable from the admin page to avoid the download entirely; if we wanted to report the deltas from the previous week, month, or quarter we could add presets for those so it wouldn't be necessary to use Excel at all; etc.

**Comment by elainekamlley** [comment]
Definitely get it. We would like to get get there and be in a position to be more specific. What would get us there is having an easier way to read it. The feedback in testing is that the export works but its hard to read and what was provided was a potential solution. If that specific solution, in your opinion, brings up larger questions, that is a bit out of scope and can be saved for the next iteration. Could you recommend a solution that could be done in this iteration that would make the data easier to read? If there not one simple solution, we can push to production and parse through the data using Excel for now.

**Comment by acdha** [comment]
I'd like to get more information about what was being done and what specifically was a challenge since the possibilities are fairly open but here are a few ideas in roughly increasing level of effort:

* #721 will add the ability to filter the list of reports before exporting it
* If the goal is to change the order so things are displayed in sections by campaign we could change the export to sort them by campaign first and then date so it'd be faster to review the list
* If the goal is just to easily get a few recent numbers, we could add those to the change list display so a download isn't even necessary (this would also get the standard sorting behaviour)
* Changing the export format to Excel would allow passing the date column as Excel's date format which would be easier to display and filter than the ISO 8601 timestamps which Excel doesn't know how to parse.
* Changing the export from the simple CSV data model to export in Excel format would allow adding some custom code to generate one sheet per campaign

**Comment by elainekamlley** [comment]
@acdha sounds good. We'll push to production with this current iteration but I'm interested to see how #721 will work when we test it.

**Comment by lalgee** [comment]
Filtering within excel does give the view shown above but it doesn't allow you to work easily with the individual datasets -- for example you would have to copy and paste each view into separate tabs or files to be able to have graphs for each as we're currently doing in google docs.  That said, I still have not had a chance to try out Kibana and see what daily reporting functionality it fulfills and #721 also sounds like it would help meet these needs.

**Comment by acdha** [comment]
Excel graphs should have the option to only plot visible rows but it sounds like we should change the default sorting and then change it to export XLSX so we can generate multiple sheets.

**Comment by rstorey** [comment]
The changes made in #721 allow filtering the existing Django admin site report by campaign. We still need to:
- [ ] Export XSLX instead of CSV / Excel so we can support multiple sheets
- [ ] Put each campaign on its own sheet

**Comment by rstorey** [comment]
The excel export utility we're using doesn't support sheets. The best we can do is to either:
1. Export one campaign at a time using the list filters in Django admin for Site Reports
2. Download the whole thing using the Site Report and then apply a Category sort on Campaign in Excel to group by Campaign.
