### ISSUE TITLE
Create wireframes for next iteration of filtering and asset view

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#770]
**Additional context**
The product team participated in a design studio to capture initial ideas to improving the experience of reviewing transcriptions for users. What came out of the workshop was building towards an interface where users can navigate the application to find what they want to work on. 

**Acceptance Criteria**
Low fidelity wireframes to capture initial concepts of: 
- [ ] flat filtering
- [ ] Asset view with a focus user choosing an activity track

**Acceptance Test:**
Add a list of steps to test for a user to check if functionality satisfies the acceptance criteria.

**Comment by jbresner** [comment]
![flat view - all items](https://user-images.githubusercontent.com/4275957/52351892-9f6fa380-29f9-11e9-8423-c4d0841ccb32.png)
![flat view - campaigns filter menu](https://user-images.githubusercontent.com/4275957/52351893-9f6fa380-29f9-11e9-97ae-dd80f1a77016.png)
![flat view - context menu](https://user-images.githubusercontent.com/4275957/52351895-a0083a00-29f9-11e9-9bc2-c3c6a46504a7.png)
![flat view - hover state](https://user-images.githubusercontent.com/4275957/52351896-a0083a00-29f9-11e9-8f9c-e3d65c40281a.png)
![flat view - sort menu](https://user-images.githubusercontent.com/4275957/52351897-a0083a00-29f9-11e9-957e-2cd36ddcb141.png)
![flat view - status filter menu](https://user-images.githubusercontent.com/4275957/52351898-a0083a00-29f9-11e9-9bf7-0806f445b13d.png)
![review](https://user-images.githubusercontent.com/4275957/52351919-a5fe1b00-29f9-11e9-9440-9883db28c9c7.png)
![browse assets - opened](https://user-images.githubusercontent.com/4275957/52351925-a991a200-29f9-11e9-80b9-5ffd1bacb4ed.png)

**Comment by acdha** [comment]
My initial reaction is that I'd like the activity to be more obvious – both because that's the goal of this view and because as a practical matter it makes the list of assets more tractable since you're only seeing things you can work on. This also makes the tabbed UI a little simpler since it will only ever have two tabs (either Transcribe or Review, and Tag), although we still have the question of discoverability (when we used tabs before the non-default tab tended to be ignored).

I'm also thinking that we might want to ditch pagination here — this is a potentially very big list which will change rapidly and beyond the technical challenges I'm not sure how useful it'd be to allow paging deeply.

**Comment by jbresner** [comment]
![transcribe - view thumbnails](https://user-images.githubusercontent.com/4275957/52365214-0058a500-2a15-11e9-8428-73e3441594e1.png)

**Comment by jbresner** [comment]
![flat view - all items - hover](https://user-images.githubusercontent.com/4275957/53891786-16985780-3ff9-11e9-960d-77db2c06727d.png)
![flat view - all items](https://user-images.githubusercontent.com/4275957/53891787-16985780-3ff9-11e9-9ccf-b41bfdc31ffc.png)
![asset view - account](https://user-images.githubusercontent.com/4275957/53891794-19934800-3ff9-11e9-86be-591563773b51.png)
![asset view - browse](https://user-images.githubusercontent.com/4275957/53891795-19934800-3ff9-11e9-96bd-e8abcd49ba14.png)
![asset view - help](https://user-images.githubusercontent.com/4275957/53891796-19934800-3ff9-11e9-91b2-7f1d1f2b4189.png)
![asset view - more info](https://user-images.githubusercontent.com/4275957/53891797-19934800-3ff9-11e9-9012-06f4a1cd5ff5.png)
![asset view - nextprev - img2](https://user-images.githubusercontent.com/4275957/53891798-1a2bde80-3ff9-11e9-8479-5d02ca867063.png)
![asset view - nextprev](https://user-images.githubusercontent.com/4275957/53891801-1a2bde80-3ff9-11e9-8428-ce1b99112a35.png)
![asset view](https://user-images.githubusercontent.com/4275957/53891802-1a2bde80-3ff9-11e9-9f9a-915f7560618f.png)

**Comment by jbresner** [comment]
Some initial comments on the new mockups...

**Flat View**
- Header is treated as if the page is an application instead of a web page (but I'm not sure this page needs this treatment...we may only want to consider this unique styling of the header for the Asset page)
- The navigation on the far right has a button for Help and a menu that could open a sign-in/register. We probably need to think about how the Help would display and also what nav would be in that hamburger menu (maybe a link back to the home page?).
- The hover state shows the same info that's in the current prototype but we should discuss if it's possible to parse the most relevant info for each item otherwise, hovering will display a lot of similar info for each item (e.g. on a lot of these, only the image number changes).

**Asset View**
- I'm not treating the page as a modal so there's no "Close" button. However, if we feel that approach makes more sense, we could make small adjustments to the UI to accommodate.
- The header nav is different than the Flat View. Part of the reason is that if we want a user to focus on the task (Transcribe or Review), the ability to sort and filter potentially takes the user off track by loading the Flat View page back AND also potentially eliminating the item the user is currently looking at from the results.
- The header nav include a link back to the Flat View (the Grid icon) and three separate buttons that slide open: Account Sign-In/Register, Help, and Browse. I'm not 100% certain of the value of this Browse UI for a user even after chatting with some folks about this. Why would a user click on an item before they're finished transcribing/reviewing a current item? Would it really benefit them to know what item is next in the queue? I suppose we could consider it as a way to get a more detailed view of the object and allow the user to decide at this more granular view if it's an item they want to transcribe/review, which might be why keeping the sort/filters is a good idea.
- I haven't added the button Rosie mentioned for indicating an item is too difficult. I just remembered I forgot it.
- Finally, there are two new buttons that are part of the asset viewer: one for displaying the previous/next items, and one that displays the meta data for the object. For the previous/next items, being able to toggle this UI might help with the limited amount of space (and for users that have no interest or need in being able to see what's there). ALSO, we have have to further refine how the previous/next items display. It should be clear that these are NOT the item being transcribed/reviewed (and in some cases, the item may be complete so it wouldn't even be an option).

**Comment by rstorey** [comment]
This work is done, for now.
