### ISSUE TITLE
Refining how asset/item/project status to be action oriented 

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#772]
**Is your feature request related to a problem? Please describe.**
As a user, when I am looking for an asset to work on OR on an asset page I need to understand what the status of an asset is, what that, means and therefore what I can do. The words we use to label and explain status is unclear and persists throughout the campaign/project/item/and asset navigation and the asset page.

Acceptance criteria: 
- Draft the names of the 4 asset/item/project status
- Updating how we display asset status on filter
- A CTA on the asset view based on status (possibly as a sentence or call to action rather than just the status name)

**Comment by VVH** [comment]
Changes to text displayed in filtering views on Project and Item pages:  


**Draft the names of the 4 asset/item/project status**
- "In progress" change to "Help transcribe"
- "Submitted for review" change to "Needs review"
- "Not started" change to "Start a new page"
- "Complete" leave as is

**A CTA on the asset view based on status (possibly as a sentence or call to action rather than just the status name)**

- "Not started / Transcription" change to "This page needs transcription. Click "Save" to save your work, and "Submit" if you transcribe the whole page and it's ready for review."
- "In progress / Transcription" change to "Someone has started a transcription. Can you finish it and submit the page for review if everything is transcribed?"
- "Submitted for Review / Transcription" change to "Thanks for reviewing! Read the transcription carefully to make sure all the text is transcribed. Click "Accept" if yes, "Edit" if no."
" Completed / Transcription" change to "This transcription has been reviewed and marked as complete."

I'm a little fuzzy on "Updating how we display asset status on filter". Is that part of the redesign plans @elainekamlley?

**Comment by acdha** [comment]
I'm not sure how some of the proposed asset status values would read when used on the pages other than the main transcription page — “Help transcribe” and “Start a new page” read more like action button text rather than reflecting the current status. Here's a quick pass in the Firefox inspector to show what that would look like:

![image](https://user-images.githubusercontent.com/46565/51568104-ee003800-1e66-11e9-8abd-c5a39c692071.png)

These would work better on the transcription page but it really seems like we should try replacing the static “Transcription” label with the call to action first.

**Comment by VVH** [comment]
Thanks for mocking this up so quickly @acdha. If I remember the meeting correctly we talked about stripping away the "Transcription" (or whatever equivalent) status information on the asset view, and just having the longer call to action language in that white space above the transcription window. So this view that you've mocked up would have these short little calls to action, but the asset window itself would not display them, and would have the longer sentences. Make sense?

**Comment by acdha** [comment]
I don’t think that reads well as a call to action. The filters show the current status and they don’t directly offer a way to change it. We could tweak that but I think those need to be description to work in the UI like e.g. change “submitted for review” to “needs review”. 

On the transcription page I would focus on the replacement calls to action where the static “Transcription” label is. That one of the places people are going to look earlier and I think it’s going to be far more significant than the status values.

**Comment by lalgee** [comment]
Semi-final drafts of updated statuses and calls to action that CM's would like to see in place.

**Asset status names**

- "In progress" leave as is (we may want to change eventually but haven't hit on the right terminology yet)
- "Submitted for review" change to "Needs review"
- "Not started" leave as is
- "Completed" leave as is

**CTA on the asset view (based on status).  To take the place of "Transcribe" above the text box.**

- For a Not started asset - "Transcribe this page."
- For a In progress asset - "Someone started this transcription. Can you finish it?"
- For a Needs review asset - "Check this transcription thoroughly. Accept if correct!”  (NOTE: alternate option for is "read" instead of "check")
- For a Completed asset - "This transcription is finished! You can read and add tags." 

Here is a screenshot I took of a CTA in place via dev tools (a little non-sensical since it doesn't match the status, but hopefully you all get the idea)
![cta](https://user-images.githubusercontent.com/20258744/51639264-7564ae80-1f2e-11e9-82ee-bd7fcc60cb73.jpg)

**Comment by elainekamlley** [comment]
@rstorey @acdha Community managers have refined this language and its ready to be implemented. Could we add this to sprint 18 as work along side the prototype? If not, it can be something to add to the prototype.

**Comment by acdha** [comment]
Where's the final language? We can review it and see whether it's a quick change or will require additional work.

**Comment by elainekamlley** [comment]
Its what @lalgee wrote above
