### ISSUE TITLE
Track how many transcriptions are exported to loc.gov

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#789]
**User story/persona**
As a community manager, I want to keep track of how many transcriptions are exported to loc.gov so that I can report to the community and to stakeholders about campaign progress.

**Acceptance Criteria**

For each export event:
- [ ]  track date and time
- [ ]  track number of items with new pages
- [ ]  track total number of pages
- [ ]  track total number of completed items (all pages in an item complete)

Stems from #385

**Comment by acdha** [comment]
There's a gap between the user story and the acceptance criteria: how are we going to know when items are actually published on www.loc.gov?

Also, it sounds like it but to be clear do these values need to be unique so that e.g. exporting the same batch 3 times would only report the deltas in the number of completed items rather than tripling the number of exported items?

**Comment by rstorey** [comment]
We won't know when items are actually published, but we'll know when we export and put the stuff on storage. There might be a need for some kind of CTS-ish report in order to be able to show unique totals.

**Comment by acdha** [comment]
I'm wondering whether we should just add an exported timestamp to the assets which is set the first time it's exported so we'd be able to easily query the unique totals at any point in time.
