### ISSUE TITLE
Track and report on length of time transcription spent in each status

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#790]
**User story/persona**
As a community manager, I want to know how long a transcription has, or set of transcriptions have, spent in each transcription status (not started, in progress, submitted) so that I can identify bottlenecks in the process and report on campaign progress.

**Acceptance Criteria**
TBD

Stems from #385

**Comment by acdha** [comment]
> I want to know how long a transcription has, or set of transcriptions have, spent in each transcription status (not started, in progress, submitted)

We have this data already stored in the database (asset creation timestamp for the duration before the first transcription record is created, transcription records for everything else) but that is probably going to be a fairly big window query. Do we have any idea of the kind of reports we want to get out of it? 

One other questions we might want to find data sources for would be things like how many times / how long someone saw a particular asset but did not actually do anything with it since that could highlight especially challenging material.

**Comment by rstorey** [comment]
This might be something that gets implemented as a Kibana visualization. I need to think more about what the end report would look like. I really like your idea of tracking how many times someone looked at something and moved on.
