### ISSUE TITLE
"Find another page" in review track should go to a review page

### ISSUE THREAD

**Issue by VVH** [LibraryOfCongress/concordia#825]
At the moment when I click "find a new page" while I'm reviewing, it takes me to a page needing transcription. We want to keep people in the review stream if that's what they've chosen to work on.

**Comment by acdha** [comment]
The UI doesn't have the concept of a track currently. That's being developed in #812 because it will requires additional UI elements to avoid confusion and make it easy for the user to select the track and know what will happen when they click on that button — for example, we could make “find next page” use the same action as the current view and that would work until the next time someone tried to edit a submitted transcription, at which point they'd silently be reverted back to transcription.

**Comment by VVH** [comment]
Ah yes, I'd forgotten about that. Thanks for the reminder @cadams. Hopefully anyone else who's interested will find this issue and also check out #812.

**Comment by elainekamlley** [comment]
This is done.
