### ISSUE TITLE
Check for pwned / weak passwords

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#835]
Use HIBP data or API (https://haveibeenpwned.com/API/v2) to check whether passwords are weak and need to be reset.

**Comment by acdha** [comment]
The tool I was wondering about using was https://github.com/ubernostrum/pwned-passwords-django but I also see https://github.com/jamiecounsell/django-pwned-passwords is out there, too. The main challenge I see is the part where it sends the hash out to HIBP rather than maintaining a local copy (which is IIRC ~30GB).

**Comment by NGTmeaty** [comment]
It only sends a [small portion of the hash to HIBP](https://github.com/jamiecounsell/django-pwned-passwords/blob/master/django_pwned_passwords/password_validation.py#L55) to compare the exact hash locally using the [k-anonymity](https://en.wikipedia.org/wiki/K-anonymity) model. This should hypothetically be entirely safe to use HIBP instead of a local copy.

**Comment by acdha** [comment]
@ngtmeaty Personally I agree and that generally seems to be the consensus view in the security community but we want to be careful to make sure we live up to the trust our patrons have that we’re protecting their privacy
