### ISSUE TITLE
Update the UI for admin simple pages around setting URL paths

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#878]
**User story/persona**
As an admin, I want to be able to add and edit simple pages within the Django admin interface so that I can provide helpful static content to users.

**Is your feature request related to a problem? Please describe.**
I know that URL paths have to be defined in `urls.py` but once they're there, we need an easy-ish process for admins to be able to create new pages. I don't think that we need to be able to change paths on existing pages, only add new ones. Now that the path setting is read-write in the django admin, there's currently nothing in the UI that would prevent an admin from making a mistake that could make the pages inaccessible.

cc: @acdha @elainekamlley

**Comment by rstorey** [comment]
Also see #985

**Comment by acdha** [comment]
I don't know that this is worth spending time on as described since it's easily noticed & corrected like any other typo. I'd vote that we close this and #985 can be turned into a ticket to use simple pages as the fallback in the 404 path so any otherwise-unused URL path can be claimed for a simple page.

**Comment by rstorey** [comment]
Closing this - caution should be exercised when editing slugs and URL paths of simple pages.
