### ISSUE TITLE
Consider adopting django-environ

### ISSUE THREAD

**Issue by acdha** [LibraryOfCongress/concordia#886]
https://github.com/joke2k/django-environ might be a good way to tame our settings files since it adds some nice features like automatic type conversion.

**Comment by rstorey** [comment]
I finally read the docs on this and it's not needed in any of the ECS environments since the settings there are actually in the environment, and the Django settings file is versioned and checked in. I could see the appeal in using it for local dev environments, but then I realized I'd be trading one unversioned unchecked in file (settings_dev_rstorey.py) for another (local .env). So I don't really see what the benefit would be, other than providing some type casting. In the examples in the docs it also makes the settings more difficult to read, IMO.

**Comment by acdha** [comment]
My thought was that it'd allow us to consolidate most of the different config files into environment usage and replacing things like `DEBUG = os.getenv("DEBUG", "").lower() == "true"` or https://github.com/LibraryOfCongress/concordia/blob/d2be83c40a7610556a5c14c622a2c08fad0e56ed/concordia/settings_template.py#L155-L159 with the automatic validation & conversion but I agree it's not a high priority.
