### ISSUE TITLE
Activity UI cleanup

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#936]
Remaining from #931 :

- [x] Cleanup Help content markup
- [x] Use correct social media icons
- [x] Make "more info" heading more prominent
- [x] Update Help content
- [x] Use a different icon for the ["another person is working on this" asset list state](https://github.com/LibraryOfCongress/concordia/blob/58d1c2327432082b809c02a4b5ec253f0b7eb8a2/concordia/static/scss/action-app.scss#L125) and possibly reconsider using CSS generated content for that
- [x] Add fullscreen icon
- [x] Refine styling of image viewer reference strip (This will be addressed in the next phase)

**Comment by acdha** [comment]
> Add fullscreen icon

Is this “Add text to the existing fullscreen icon, possibly with a responsive threshold”, “pick a different icon to indicate fullscreen mode”, or something else?

**Comment by acdha** [comment]
> Cleanup Help content markup

Is this specific to the activity UI or do we need to consider something like moving that content into an include / simple page so it can be included on both the existing asset detail & activity UI pages?

**Comment by rstorey** [comment]
> > Add fullscreen icon
> 
> Is this “Add text to the existing fullscreen icon, possibly with a responsive threshold”, “pick a different icon to indicate fullscreen mode”, or something else?

The fullscreen icon isn't in Jamie's mocks.

**Comment by rstorey** [comment]
> > Cleanup Help content markup
> 
> Is this specific to the activity UI or do we need to consider something like moving that content into an include / simple page so it can be included on both the existing asset detail & activity UI pages?

The CMs would like it to be editable a la simple pages. That would be a nice bonus.

**Comment by acdha** [comment]
That's good clarification — one of the questions there is whether we should make that one big simple page or if that's really two separate pages because e.g. we want to use the same image viewer keyboard shortcut list and help center text in both OpenSeadragon instances and both transcribe UIs, respectively, but those aren't the same block in both.

There's a side issue here that the keyboard help also needs to be marked as specific to the image viewer rather than global, which is how we ended up with two separate help buttons.

**Comment by jbresner** [comment]
Quick question..I think it may have been answered before but just in case...why are we displaying items that can't be reviewed (in the case where someone else is working on it).

**Comment by acdha** [comment]
@jbresner The short answer is that the statuses can change while someone is looking the list and we are trying to avoid having things inexplicably disappear or, especially, change the list position as would happen if we removed any asset above the current viewport.

A couple of sequences which come to mind:

1. User is reviewing and clicks “Edit” to reopen an transcription for additional work
2. The asset is now ineligible for review but in addition to keeping their position in the list stable we might want to streamline the process of being able to select it & switch to transcribing it without having to search for it in the list.

1. Someone is scrolling through the list
2. Someone else opens one of the available assets, so it's now badged as “someone else is working on this”
3. This could lead to multiple possible outcomes:
    * The other person navigates to a new asset without doing anything, at which point it becomes available to work on again
    * The other person changes the state of the asset – submitting a transcription for review, sending a submitted item back for improvements, or accepting – and it is now unavailable for the current activity but anyone is free to look at it either out of curiosity or because it's related to something they're working on

**Comment by jbresner** [comment]
> > > Add fullscreen icon
> > 
> > 
> > Is this “Add text to the existing fullscreen icon, possibly with a responsive threshold”, “pick a different icon to indicate fullscreen mode”, or something else?

> The fullscreen icon isn't in Jamie's mocks.

We can add it back to the header but it's something I'd recommend checking the analytics over time to see if it's getting used (I removed it from a previous design when I felt the header was getting cluttered). Another issue to consider is how browsers provide a similar functionality. Chrome's full-screen button does exactly the same thing (other browsers appear to main some of the browser UI in their full-screen mode).

**Comment by rstorey** [comment]
That's a good point about the full screen icon. @elainekamlley ? @colefemeno ? thoughts?

**Comment by acdha** [comment]
> We  can add it back to the header but it's something I'd recommend checking  the analytics over time to see if it's getting used (I removed it from a  previous design when I felt the header was getting cluttered). 

Having it stay in full-screen mode was one of the goals for making the entire UI client-side so it would be important not to use any of the existing analytics for this. 

> Another  issue to consider is how browsers provide a similar functionality.  Chrome's full-screen button does exactly the same thing (other browsers  appear to main some of the browser UI in their full-screen mode).

We provide the full-screen button so the experience is more consistent. Microsoft Edge may or may not have a full-screen mode depending on the version (some releases used F11, some use the emerging Windows 10 shortcut Windows-Shift-Enter, and there is not consistently an equivalent menu option) and of the portable browsers there tends to be different behaviour based on the OS version: for example, Chrome, Firefox, and Safari all leave the browser location bar, tab controls, and bookmarks menu visible on Mac OS but not Windows 10, and at least historically the behaviour also varied on multi-display systems. iOS Safari has heuristics to collapse the menu bar but since our app fits to the viewport those don't reliably work and they still use a fair percentage of the vertical height on anything less than an iPad Pro.

In contrast, the HTML5 full-screen API reliably dedicates the entire current display to the app without any browser chrome, needing to memorize keyboard shortcuts, or toggle the preferences to display the menu/location/bookmarks toolbars.

**Comment by elainekamlley** [comment]
Chatted with @colefemeno and we agree to add it back into the prototype. I'll make sure I work with @lalgee and Leah to capture the usage of that feature in our analytics.

**Comment by elainekamlley** [comment]
> 2\. The asset is now ineligible for review but in addition to keeping their position in the list stable we might want to streamline the process of being able to select it & switch to transcribing it without having to search for it in the list.

I noticed the hard line between transcription and reviewing. Editing is a key characteristic of reviewing a transcription and even our users get a little frustrated that they have to resubmit it for review especially if the edit is small. What are your thoughts on a good solution to this?

**Comment by acdha** [comment]
> I noticed the hard line between transcription and reviewing. Editing is a key characteristic of reviewing a transcription and even our users get a little frustrated that they have to resubmit it for review especially if the edit is small. What are your thoughts on a good solution to this?

I think it will improve over time but it will require a lot of work because switching modes affects almost everything you see. At the very least we'll want to add support for switching between modes while maintaining current asset selection — which likely means restoring the mode selector to the header where I originally had it before it was moved to be part of the asset list filters to follow the comps — so you can start out reviewing, switch to editing, and work on the same item. 

That might want some prompting (“Do you want to edit this now or keep reviewing?”, “Do you want to go back to reviewing?” after editing, etc.) or some visual indication of the history but we'll want to test more as we go along.

**Comment by jbresner** [comment]
Should we just add the mode selector back now? I only removed it since I felt the activity screen should be simplified for the selected task (transcribing or reviewing). If the thinking is that users are going to want to constantly have the option to change the activity and or the filters, shouldn't we just keep it persistently displayed?

**Comment by jbresner** [comment]
Can anyone elaborate on why the "lock" icon is a bad choice for an asset currently being worked on? I'm not sure what to consider replacing it with without knowing why the first choice wasn't adequate. Or were we just looking for styling of the notification message overlaid on images?

**Comment by elainekamlley** [comment]
@jbresner Its about how can our icons convey community. While the lock is a good indicator that the asset is taken, it signals restriction rather than collective work to complete something together. I think of something like google slides where you see a person's icon or an animal. A simple silhouette person icon would be a good option.

**Comment by jbresner** [comment]
So something more like this: using an "user" icon and also changing the color from red, which seems overboard for a basic notification, and using a lighter hue of the LOC blue as a background color:

![Asset View - Default View](https://user-images.githubusercontent.com/4275957/57476030-b8d7f400-7263-11e9-83b7-427dd1da751c.png)
![Flat View - Help](https://user-images.githubusercontent.com/4275957/57476031-b8d7f400-7263-11e9-88a6-f250b6fc4e2b.png)

The messaging might still need fine-tuned but this feels less dramatic than the red lock.

**Comment by rstorey** [comment]
> > I noticed the hard line between transcription and reviewing. Editing is a key characteristic of reviewing a transcription and even our users get a little frustrated that they have to resubmit it for review especially if the edit is small. What are your thoughts on a good solution to this?
> 
> I think it will improve over time but it will require a lot of work because switching modes affects almost everything you see. At the very least we'll want to add support for switching between modes while maintaining current asset selection — which likely means restoring the mode selector to the header where I originally had it before it was moved to be part of the asset list filters to follow the comps — so you can start out reviewing, switch to editing, and work on the same item.
> 
> That might want some prompting (“Do you want to edit this now or keep reviewing?”, “Do you want to go back to reviewing?” after editing, etc.) or some visual indication of the history but we'll want to test more as we go along.

If you're viewing a specific asset, for example in Review mode, and you click Edit and choose to continue editing that asset, let's say it automatically switches you from Review to Transcribe. That means it repopulates the asset list, doesn't it?

**Comment by rstorey** [comment]
> Should we just add the mode selector back now? I only removed it since I felt the activity screen should be simplified for the selected task (transcribing or reviewing). If the thinking is that users are going to want to constantly have the option to change the activity and or the filters, shouldn't we just keep it persistently displayed?

I'm still not sure what the behavior should be on this. I'm unclear on when and whether the asset list gets refreshed or re-sorted based on the user's actions while in either mode, or while switching modes. I think if the mode changes makes the entire asset list refresh, it has to be displayed. But, I'm not sure that has to be or should be the case.

**Comment by acdha** [comment]
> If you're viewing a specific asset, for example in Review mode, and you click Edit and choose to continue editing that asset, let's say it automatically switches you from Review to Transcribe. That means it repopulates the asset list, doesn't it?

We keep all of the asset data loaded now so switching modes is less expensive than it used to be. It will redraw the asset list but [`getVisibleAssets()`](https://github.com/LibraryOfCongress/concordia/blob/3def804615b0fddfe94239c47a49005aec17dc54/concordia/static/js/action-app/index.js#L706-L759) has support for keeping a specified asset visible even if it would otherwise be excluded, which is what we use to prevent the current asset from disappearing as soon as you submit/accept/reject it.

Right now this would probably be something like:
1. Click “Edit”
2. Choose the option to switch to transcribing
3. Update the transcription & save / reject
4. This step needs would need to be improved: if you wanted to switch back to reviewing right now you'd have to know that if you close the viewer you can then choose the mode selector from the asset list filter toolbar. If that bumped into the header it'd avoid those steps but perhaps still not be obvious enough. Making the flow smoother and making it seamless to keep the same asset selected throughout would be an argument for some sort of non-modal prompt which could allow you to switch back to the previous mode as close to the point where you were as possible.

**Comment by acdha** [comment]
> I'm unclear on when and whether the asset list gets refreshed or re-sorted based on the user's actions while in either mode, or while switching modes. I think if the mode changes makes the entire asset list refresh, it has to be displayed. But, I'm not sure that has to be or should be the case.

[`updateAssetList()`](https://github.com/LibraryOfCongress/concordia/blob/3def804615b0fddfe94239c47a49005aec17dc54/concordia/static/js/action-app/index.js#L614-L644) gets the visible items (i.e. the status is valid for the current mode, we've fully loaded its metadata, it matches the active campaign filter if any), sorts them, and updates the display. That method is called when one of those factors is invalidated.
