### ISSUE TITLE
Activity UI: display prev / next asset pages

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#938]
From #930 

> When moving to next and previous page I only saw the image in the viewer, I expected to see the accompanying title and transcription 

@rstorey:

> This has to do with the above item "What should the adjacent pages section of the OpenSeadragon viewer look like? i.e. how do we indicate which page you're transcribing and which ones are just there for context?" as well as the item in the Deferred Features from #812 which talked about only loading the previous and next images for reference, and not for navigation - not loading the transcription data or other metadata. If that's truly a requirement, we need to rethink using the OpenSeadragon reference viewer for this purpose and instead put in a second asset list. Also, if we change the asset in the viewer when you go prev or next, you'll lose any unsaved work as well as your asset reservation).

**Comment by acdha** [comment]
I think the intention has always been to use a custom view rather than the OpenSeadragon image strip but we have a bunch of UI issues to work through regarding how we distinguish between changing which page you're working on and seeing context, and whether we support things like history popping between assets and/or switching modes quickly.

**Comment by rstorey** [comment]
Dupe of #1000
