### ISSUE TITLE
Saved transcription text clobbers textarea input in Activity UI

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#949]
**What behavior did you observe? Please describe the bug**
The text I entered in the textarea as I was transcribing was reverted to the last saved transcription.

**How can we reproduce the bug?**

1. Load the Activity UI.
2. Click Transcribe.
3. Open an asset.
4. Enter some text in the textarea.
5. Wait about a minute.

**What is the expected behavior?**
The text I entered in the textarea should remain.

**Comment by acdha** [comment]
We need to always make that update call because the text is not the only thing which can change. I think the answer is probably changing the text editor component to track the value which was set before any changes were made and then making the policy decisions about what happens in the various non-default flows (e.g. do we nag if you try to leave without saving, what happens if you lose the lock, etc.?)

**Comment by rstorey** [comment]
Fixed in crowd-dev
