### ISSUE TITLE
Transcription text in activity UI doesn't match text in classic UI

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#986]
**What behavior did you observe? Please describe the bug**
* The latest version of the transcription text is not always loaded - it does not match what is shown in the classic UI. 

**How can we reproduce the bug?**

1. Go to the activity UI in Chrome browser.
1. Click Transcribe.
1. Sort by most difficult in order to get some assets in the list that have multiple transcription text versions.
1. Copy and paste the URL and open it in Safari and Firefox. 
1. Note the transcription text and refresh the browser.
1. Refresh the URL in Chrome as well.

**What is the expected behavior?**

The text for the current asset should be displayed filling the available content area

**Got screenshots? This helps us identify the issue**
![Screen Shot 2019-05-21 at 5 41 52 PM](https://user-images.githubusercontent.com/5270415/58132632-ce4c0700-7bef-11e9-97a2-9a884bcb88ba.png)

**Desktop (please complete the following information):**

-   OS: Mac
-   Browse: Chrome, Safari, Firefox

**Additional context**
* This is the URL in the screenshot: https://crowd-dev.loc.gov/act/#mode=transcribe&sort=hardest&asset=40967

*  the data is always correctly loaded (confirm with `actionApp.assets.get(actionApp.openAssetId).latest_transcription`) but the display varies:
* #991: A CSS regression causes the text area to be only a couple of lines tall (previously it stretched to fill the full height), and the browsers are not 100% consistent in the default scroll positions. We need to fix this anyway.
* When an asset is already reserved by someone else, the initial attempt to get the lock fails and that disrupts changing the textarea value from whatever the previous asset had been. When I tested it, this resolved when it got the lock.

**Comment by rstorey** [comment]
As you can see in the screenshot I posted, I had the reservation lock but the transcription text was an older version and not the latest text.

**Comment by acdha** [comment]
I changed the description to match what happened in the debugger. We need to restore the earlier CSS (not sure if @klee72 has time) to get the height to be consistent and we need to make sure that failing to reserve the asset still updates the textarea with the current item rather than leaving the previous contents unmodified. This should probably also clear it on close so it's more obvious and there's no delay.

**Comment by acdha** [comment]
Following the instructions given, I can't reproduce any case where an older version of the same asset is displayed. #991 makes the display consistent and the text is identical for just viewing. If you make changes in one window, they will not _display_ until you either obtain the asset lock after moving away in the other session or click on the asset again.

If you have a way to reproduce getting an older version of the same asset it would be really useful to get the output of `actionApp.assets.get(actionApp.openAssetId).latest_transcription` in both browsers so we can see whether the issue is not getting the correct data from the server or a display problem.

**Comment by rstorey** [comment]
I just reproduced it on my first try in crowd-dev. https://crowd-dev.loc.gov/act/#mode=transcribe&sort=hardest&asset=40967

The version of the transcription that starts with [?] is not the latest (saved) version.

**Comment by rstorey** [comment]
Here's another one. https://crowd-dev.loc.gov/act/#mode=transcribe&sort=hardest&asset=40966

The latest version of the transcription text (visible in the classic UI) starts with "the resources of the country" (visible here: https://crowd-dev.loc.gov/campaigns/letters-to-lincoln/1861-secession-inauguration-start-of-civil-war/mal0663900/mal0663900-3/ )

However as you can see in this screenshot, I'm getting a version of the text that starts with "the [?] of the country" - this is on my first load of the page without having made any edits to the text myself.
<img width="2125" alt="Screen Shot 2019-05-22 at 1 34 43 PM" src="https://user-images.githubusercontent.com/5270415/58195614-613f7c80-7c96-11e9-98f5-52a7d0852a6c.png">

**Comment by acdha** [comment]
Can you collect latest transcription information as seen by the app (`actionApp.assets.get(actionApp.openAssetId).latest_transcription`)? If the data being loaded doesn't match what we're seeing on the classic asset detail page we might have an issue with the way the JSON streaming view loads the latest transcription.

**Comment by acdha** [comment]
Yeah, that turns out to be the problem — and there's a race condition as well which explains why it doesn't consistently reproduce:

When you load the app with a saved asset ID, it does a separate request for just that one asset by ID:

https://crowd-dev.loc.gov/assets.json?per_page=500&pk=40967&format=json

```json
{
    "latest_transcription": {
        "id": 73634,
        "submitted_by": 2617,
        "text": "-pressing the opinion that election \r\nof Hon. Thaddeus Stevens \r\nas a Member of your Cabinet\r\nwould be most satisfactory to\r\nthe great mass of your political\r\nfriends in this state-- would\r\nsecure you a most faithful, able,\r\nand reliable counsellor, and \r\nbe productive of the best results\r\nto the public service.\r\nI have the honor to be,\r\nMost respectfully,\r\nYour very obedient servant,\r\nThomas E Cochran,\r\nAuditor General of Pennsylvania"
    }
}
```

When the assets are retrieved in bulk the response is incorrect:

```json
{
    "id": 22111,
    "submitted_by": 8,
    "text": "[?] the opinion that e-\r\nlection of him. Thaddeus Ste-\r\nvens as a Member of your Cabinet\r\nwould be most satisfactory to\r\nthe great map of your political\r\nfriends in this state--[?]\r\nsecure you a most faithful, able,\r\nand reliable counselor "
}
```

(`curl -s --fail https://crowd-dev.loc.gov/transcribe.json?per_page=500&format=json | jq '.objects[71].latest_transcription'`)

That'll race in this case because the asset in question was in the first page of results but the saved asset ID was still loaded earlier.

**Comment by acdha** [comment]
https://github.com/LibraryOfCongress/concordia/pull/994 should correct the logic for that view but testing is paused for the meeting.
